---
title: "GOA Rachel Carson 2022"
author: "Zack Gold"
date: "2024-12-23"
output: html_document
---
# Load Data

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(oce)
library(readxl)
library(ggrepel)
library(sf)
library("rnaturalearth")
library("rnaturalearthdata")
library(cmocean)

```
# Machine Readible QAQC

```{r}

sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_RC0083.csv"), header=T,fileEncoding="UTF-8")


sample_Data %>% 
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC),
         Combined_date_local = str_c(Collection_Date_local, " ",Collection_Time_local),
          Date_local_check = as.POSIXct(Combined_date_local, format="%m/%d/%y %H:%M", tz="US/Alaska"),
         Date_local_check = if_else(is.na(Date_local_check), as.POSIXct(Combined_date_local, format="%m/%d/%y", tz="UTC"), Date_local_check )) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%Y %H:%M", tz="UTC"),
                  Date_UTC = if_else(is.na(Date_UTC), as.POSIXct(Collection_Date_UTC, format="%m/%d/%Y", tz="UTC"), Date_UTC ), 
         Date_local= format(Date_UTC,tz="US/Alaska"),
         Lat_fix=NA,
         Lon_fix=NA) %>% 
  mutate(., Lat_dec = as.numeric(Lat)) %>% 
  mutate(., Lon_dec=as.numeric(Lon)) %>% 
  mutate(., Cast=as.character(Cast_No.),
         Bottle=as.character(Rosette_position)) -> QAQCMRE_CruiseSampleMetadata_RC0083


c("Sample_Name","Biological_Replicate","Technical_Replicate","Negative_control",    "Cruise_ID_short",     "Cruise_ID_long",     "Collection_Date_UTC", "Collection_Date_local","Collection_Time_UTC","Collection_Time_local"                   ,"Field_Sample_Name",   "Cast_No.",  "Rosette_position",    "Field_collection_method"       ,"Preservation",       "Area.within.region",  "Station",    "Depth_m",   
"Lat",        "Lon",        "Sample_volume_ml",   
"Personnel_responsible_for_Collecting_Sample", "Field_Notes","Combined_date",      "Combined_date_local", "Date_UTC",   "Date_local_check",   
"Date_local", "Lat_fix",    "Lat_dec",   
"Lon_fix",    "Lon_dec",    "Cast",      
"Bottle"   ) -> skq1_colnames

colnames(QAQCMRE_CruiseSampleMetadata_RC0083)
setdiff(skq1_colnames,colnames(QAQCMRE_CruiseSampleMetadata_RC0083) )
setdiff(colnames(QAQCMRE_CruiseSampleMetadata_RC0083),skq1_colnames )

QAQCMRE_CruiseSampleMetadata_RC0083 <- QAQCMRE_CruiseSampleMetadata_RC0083[, skq1_colnames]

readr::write_excel_csv(QAQCMRE_CruiseSampleMetadata_RC0083, file="QAQCMRE_CruiseSampleMetadata_RC0083.csv")



```

```{r}

min_lat <- min(QAQCMRE_CruiseSampleMetadata_RC0083$Lat_dec, na.rm = T)
max_lat <- max(QAQCMRE_CruiseSampleMetadata_RC0083$Lat_dec, na.rm = T)

min_lon <- min(QAQCMRE_CruiseSampleMetadata_RC0083$Lon_dec, na.rm = T)
max_lon <- max(QAQCMRE_CruiseSampleMetadata_RC0083$Lon_dec, na.rm = T)

world <- ne_countries(scale = "medium", returnclass = "sf")
QAQCMRE_CruiseSampleMetadata_RC0083$Date_UTC %>% as.Date() -> dates


ggplot(data = world) +
    geom_sf() +
    geom_point(data = QAQCMRE_CruiseSampleMetadata_RC0083, aes(x = Lon_dec, y = Lat_dec, colour=as.Date(Date_UTC)), size=2) +
    coord_sf(xlim = c(min_lon-1, max_lon+1), ylim = c(min_lat-1, max_lat+1), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +
  geom_text(data = QAQCMRE_CruiseSampleMetadata_RC0083, aes(x = Lon_dec, y = Lat_dec, label=Station),size = 2, colour="black") + scale_color_cmocean(labels=dates, breaks=dates, name ="tempo", start = 0.1, end=0.5) +labs(colour="Date")


```

```{r}
QAQCMRE_CruiseSampleMetadata_RC0083 %>% 
  filter(., is.na(Lat_dec))
```

```{r}
QAQCMRE_CruiseSampleMetadata_RC0083 %>% 
  ggplot() +
  geom_point(aes(y = Lat_dec, x =as.Date(Date_UTC), colour=as.Date(Date_UTC)), size=2) + scale_color_cmocean(labels=dates, breaks=dates, name ="tempo", start = 0.1, end=0.5) +labs(colour="Date") +scale_x_date(date_labels = "%b %d %Y")
```


# Read Bottle Data 1

```{r}
### Identify the list in the directory
files = dir(path = here("CTD_raw_BottleFile_RC0083"), pattern = ".cnv", full.names = TRUE )

## preallocate the container to store the individual 
bottle = list()

### Loop the CNV file and create a list of casted CTD
for (i in 1:length(files)){
  
bottle[[i]]  = read.ctd(files[i])%>%
  ctdTrim(method = "downcast")%>% # select downcast
  ctdDecimate(p = 1) # align to the same standard pressure
}

bottle[[1]] %>% 
  oce::plot(eos = "unesco",
  useSmoothScatter = FALSE, grid = F,
  showHemi = FALSE, 
  drawIsobaths = TRUE)

summary(bottle[[1]])
```

```{r}

str_remove(files, "/Users/zgold/Documents/PMEL/Science/EcoFOCI/data/1_SampleCollection/2022_GOA-OA_CruiseData/CTD_raw_BottleFile_RC0083/") %>% 
  str_remove(., ".cnv") -> cast_names

datalist = vector("list", length = length(cast_names))

for (i in 1:length(files)){
  
datalist[[i]] = bottle[[i]]@data%>%
  as_data_frame() %>% 
  mutate(., Cast= cast_names[i])
}

ctd.tb = do.call(rbind, datalist)
bottle[[i]]@metadata
```



```{r}
### Identify the list in the directory
files = dir(path = here("CTD_raw_BottleFile_RC0083"), pattern = ".btl", full.names = TRUE )

## preallocate the container to store the individual 
bottle = list()

### Loop the CNV file and create a list of casted CTD
for (i in 1:length(files)){
  
bottle[[i]]  = read.ctd.sbe(files[i], btl = T)
}
```

```{r}

str_remove(files, "/Users/zgold/Documents/PMEL/Science/EcoFOCI/data/1_SampleCollection/2022_GOA-OA_CruiseData/CTD_raw_BottleFile_RC0083/") %>% 
  str_remove(., ".btl") -> cast_names

datalist = vector("list", length = length(cast_names))

for (i in 1:length(files)){
  
datalist[[i]] = bottle[[i]]@data%>%
  as_data_frame() %>% 
  mutate(., Cast= cast_names[i])
}

bottle_Data = do.call(rbind, datalist)
```


```{r}
bottle_Data %>% 
  mutate(.,
         Cast = str_remove(Cast,"RC0083_")) %>% 
           mutate(., Cast = as.numeric(Cast)) %>% 
   rename_with(.fn = ~ paste0("btl_", .x))-> bottle_Data

bottle_Data$Cast <- as.character(bottle_Data$btl_Cast)
bottle_Data$bottle <- as.character(bottle_Data$btl_Bottle)
```

# Read Bottle Data 2
```{r}
bottle_carbonate <- read.csv(file= here ("RC0083 w pH Z.Gold 12.06.24.csv"), header=T)

 bottle_carbonate %>% 
   rename_with(.fn = ~ paste0("btl2_", .x)) -> bottle2_Data

   
bottle2_Data$Cast <- as.character(bottle2_Data$btl2_Cast_number)
bottle2_Data$bottle <- as.character(bottle2_Data$btl2_Rosette_position)
```
# Merge Sample, Bottle, and CTD Data


```{r}
QAQCMRE_CruiseSampleMetadata_RC0083 %>% 
    mutate(pressure= round(Depth_m,0)) %>% 
  left_join(bottle_Data, by = c("Cast" = "Cast", "Bottle" = "bottle"))  %>%  
    left_join(bottle2_Data, by = c("Cast" = "Cast", "Bottle" = "bottle"))  %>%
  mutate(., Date_UTC_btl = as.POSIXct(`btl_time`, format="%Y-%m-%d %H:%M:%S", tz="UTC") ) -> GOA_OA_2022_Cruise_sample_data


#colnames(ctd_Data)[2:47] -> cols_2_keep
library(rlang)

GOA_OA_2022_Cruise_sample_data %>% 
  mutate(., verbatimCoordinateSystem = case_when(!is.na(Lon) & !is.na(Lat) ~ "decimal degrees", TRUE ~ NA_character_)) %>%
  select(Sample_Name, 
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Station,
         Depth_m_notes=Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         verbatimEventDate = Collection_Date_local,
         verbatimEventTime = Collection_Time_local,
         verbatimLongitude = Lon,
         verbatimLatitude = Lat,
         verbatimCoordinateSystem,
         Date_UTC_btl,
        # !!!syms(cols_2_keep),
                starts_with("ctd"),
        starts_with("btl")
        ) -> GOA_OA_2022_Cruise_sample_data


readr::write_excel_csv(GOA_OA_2022_Cruise_sample_data, file="FinalOME_Merge_RC0083.csv")
```

```{r}
GOA_OA_2022_Cruise_sample_data %>% 
  dplyr::select(contains("ox"),contains("Ox") )

colnames(GOA_OA_2022_Cruise_sample_data) 
```

