---
title: "GOA Rachel Carson 2022"
author: "Zack Gold"
date: "2024-07-03"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(oce)
library(readxl)

library(cmocean)
library(ggpubr)
library(patchwork)
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(readxl)
library(sf)
library(devtools)
#devtools::install_github("katiejolly/nationalparkcolors")
library(nationalparkcolors)
library(knitr)
library("rnaturalearth")
library("rnaturalearthdata")
library("readxl")
library(parzer)

world <- ne_countries(scale = "medium", returnclass = "sf")

```


```{r}
read.csv(here("data","1_SampleCollection","2022_GOA-OA_CruiseData","FinalOME_Merge_RC0083.csv")) -> GOA_OA_2022_Cruise_sample_data

```


# Load in Jonah Venture Data
```{r}
samples_uc <- read_excel(here("RC008_sample_under_consideration.xlsx"))

samples_uc %>% 
  dplyr::select(Sample_ID) %>% 
  mutate(., Sample_Name = str_remove(Sample_ID,"RC0083")) %>% 
  left_join(GOA_OA_2022_Cruise_sample_data) %>% 
  mutate(., Depth_bin = case_when( Depth_m < 10 ~"Surface",
                                   Depth_m < 100 ~ "Mid",
                                   TRUE ~"Deep")) -> uc_data

write_excel_csv(uc_data, file = here("GOA_OA_2022_Cruise_sample_data_20241031.csv"))
          
```

```{r}



min_lat <- min(uc_data$Latitude, na.rm = T)
max_lat <- max(uc_data$Latitude, na.rm = T)

min_lon <- min(uc_data$Longitude, na.rm = T)
max_lon <- max(uc_data$Longitude, na.rm = T)

library(ggrepel)
ggplot(data = world) +
    geom_sf() +
    geom_point(data = uc_data, aes(x = Longitude, y = Latitude, colour=Ph), size=2) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +
  geom_text_repel(data = uc_data, aes(x = Longitude, y = Latitude, label=Station),size = 2) +facet_grid(.~Depth_bin) +scale_color_cmocean()

ggsave(file=here("map_pH_RC0083.png"), width = 12, height = 8)

```

```{r}

GOA_OA_2022_Cruise_sample_data %>% 
  mutate(., Included = if_else(Sample_Name %in% uc_data$Sample_Name, "Included","Excluded")) -> to_plot_map


min_lat <- min(uc_data$Latitude, na.rm = T)
max_lat <- max(uc_data$Latitude, na.rm = T)

min_lon <- min(uc_data$Longitude, na.rm = T)
max_lon <- max(uc_data$Longitude, na.rm = T)

library(ggrepel)
ggplot(data = world) +
    geom_sf() +
    geom_point(data = to_plot_map, aes(x = Longitude, y = Latitude, colour=Included), size=2, alpha =0.2) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +
  geom_text_repel(data = to_plot_map, aes(x = Longitude, y = Latitude, label=Station),size = 2)

ggsave(file=here("map_pH_RC0083_included_excluded.png"), width = 12, height = 8)

```


```{r}

 uc_data %>% 
  group_by(Station) %>% 
  dplyr::summarise(n_distinct(Sample_Name), maxPh = max(Ph, na.rm = T), minPh = min(Ph, na.rm = T)) -> sample_summed 

sample_summed %>% 
arrange(desc(`n_distinct(Sample_Name)`))

uc_data %>% 
  filter(., Station =="LC1")

uc_data %>% 
  filter(., Station =="JH3")

uc_data %>% 
  filter(., Sample_Name =="E1562.")

sample_summed %>% 
  ggplot(aes(y=maxPh, label=Station, x=minPh)) +geom_label_repel()

ggsave(file=here("pH_plot_RC0083.png"), width = 12, height = 8)


sample_summed %>% 
  mutate(., difPH= maxPh-minPh) %>% 
  filter(., 8.4 > maxPh & maxPh > 8.2)

```

```{r}

 uc_data %>% 
  ggplot(aes(y=Depth_bin, x=Station, fill=Ph)) +geom_tile()

ggsave(file=here("pH_tile_plot_RC0083.png"), width = 12, height = 8)

```

```{r}
uc_data %>% 
  ggplot(aes(y=Depth_m, x=Station, colour=Ph, label=Sample_Name)) +geom_point()

ggsave(file=here("depth_plot_RC0083.png"), width = 12, height = 8)


uc_data %>% 
  filter(., Depth_m > 550)
```

# Analysis
```{r}

GOA_OA_2022_Cruise_sample_data
long_COI_EcoFOCI <- readRDS(here("data","long_data","long_COI_EcoFOCI.RDS"))


long_COI_EcoFOCI %>% 
    filter(., Cruise_ID_short =="RC_GOA_2022") %>%  
  dplyr::select(ASV_combo, `Run2:ASV`, `Run3:ASV`,`Run4:ASV`, Sequence,Kingdom, Phylum,Class,Order,Family,Genus,Species,Sample,Sample_Name, nReads,eDNA.Index) %>% 
  left_join(GOA_OA_2022_Cruise_sample_data) -> goa22_long



```

## Group by Species

#### Build Phyloseq Object

```{r}

varnames <- colnames(goa22_long)
to_remove <- c("Run2:ASV","Run3:ASV","Run4:ASV","ASV_combo","Sequence","nReads","Prop.abund","eDNA.Index")
to_remove2 <- c("Kingdom","Phylum","Order","Class","Family","Genus","Species")


goa22_long %>% 
  ungroup() %>% 
  dplyr::select(c(setdiff(setdiff(varnames,to_remove),to_remove2))) %>% distinct() -> goa_co1_sample_data

#Metadata
goa_co1_sample_data %>%  as.data.frame() -> sampledata
rownames(sampledata) <- sampledata$Sample
sample_data(sampledata) -> sampledata

#ASV Reads

c(setdiff(varnames,to_remove),"Tot") -> varnames_to_group

goa22_long %>% 
  dplyr::select(-eDNA.Index) %>% 
  ungroup() %>% 
 group_by(Sample) %>%
    mutate(Tot = sum(nReads)) %>% 
    group_by(!!!syms(varnames_to_group)) %>% 
    dplyr::summarise(nReads=sum(nReads)) %>% 
    mutate (Prop.abund = nReads / Tot) %>% 
      ungroup() %>% 
    unite(sum.taxonomy, c("Kingdom",              "Phylum",               "Class"               
,"Order",                "Family",               "Genus",               "Species"), sep=";") %>% 
    group_by (sum.taxonomy) %>%
    mutate (Colmax = max(Prop.abund),
            eDNA.Index = Prop.abund / Colmax) %>% 
  dplyr::select(sum.taxonomy,Sample, eDNA.Index) %>% 
  mutate(., eDNA.Index=as.numeric(eDNA.Index)) %>% 
  mutate(., eDNA.Index=if_else(eDNA.Index=="NaN", 0, eDNA.Index)) %>%
  pivot_wider(names_from = Sample, values_from = eDNA.Index, values_fill  =0) -> wide_PA_goa

wide_PA_goa %>% 
  dplyr::select(sum.taxonomy) %>% 
   separate(sum.taxonomy, into=c("Kingdom",              "Phylum",               "Class"               
,"Order",                "Family",               "Genus",               "Species"), sep=";", remove=F) %>%  
  dplyr::select(sum.taxonomy, Kingdom,Phylum,Class, Order,Family, Genus, Species) %>% 
  distinct() %>% as.matrix() -> taxonomy_table
dim(taxonomy_table)
dim(wide_PA_goa)

rownames(taxonomy_table) <- wide_PA_goa$sum.taxonomy

TAX = tax_table(taxonomy_table)

wide_PA_goa %>% 
  ungroup() %>% 
  dplyr::select(-sum.taxonomy) %>% as.matrix() -> otu_table
rownames(otu_table) <- wide_PA_goa$sum.taxonomy

OTU = otu_table(otu_table, taxa_are_rows = TRUE)
physeq_obj._CO1_sum.tax_goa = phyloseq(OTU, TAX, sampledata)

```


##  All Bray

```{r}
physeq_obj._CO1_sum.tax_goa <- prune_samples(sample_sums(physeq_obj._CO1_sum.tax_goa) > 0, physeq_obj._CO1_sum.tax_goa)
physeq_obj._CO1_sum.tax_goa = subset_taxa(physeq_obj._CO1_sum.tax_goa, Kingdom!="Bacteria")
physeq_obj._CO1_sum.tax_goa = subset_taxa(physeq_obj._CO1_sum.tax_goa, Kingdom!="Environmental Unknown")

physeq_obj._CO1_sum.tax_goa = subset_samples(physeq_obj._CO1_sum.tax_goa,
                                             !is.na(btl_Ph) & 
                                               !is.na(btl_T090C) & 
                                               !is.na(btl_OxsatMm.Kg) &
                                               !is.na(btl_Latitude)&
                                               !is.na(btl_Longitude) & !is.na(btl_Sal00))

tax_table(physeq_obj._CO1_sum.tax_goa) %>%  as.data.frame()
```


```{r}

#Betadiversity
#Generate Vegan formatted data table
method.sampledf <- data.frame(sample_data(physeq_obj._CO1_sum.tax_goa))
method.rel_abun<- vegan_otu(physeq_obj._CO1_sum.tax_goa)

#Bray dissimilarity matrix
method.d_carn <- vegdist(method.rel_abun, method="bray")

#PERMANOVA: Method+Site

method.adonis_results_goa <- adonis2(method.rel_abun~btl_Ph+btl_T090C+btl_OxsatMm.Kg+Depth_m_notes+btl_Latitude+btl_Longitude+btl_Sal00, data=method.sampledf, by = "terms",na.action =na.exclude)

method.adonis_results_goa

```

```{r}
ord <- ordinate(physeq_obj._CO1_sum.tax_goa, method = "NMDS", distance = ("bray"))
```

### NMDS Temp
```{r}
##Plot_Ordination
plot_ordination(physeq_obj._CO1_sum.tax_goa, ord, "samples",color = "btl_Ph") +
  ggtitle(paste0("NMDS - Stress ",round(ord$stress,3))) + 
  geom_point(size = 4) + 
  theme_bw()+ 
  theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5,size = 18, face = "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.text=element_text(size=16), 
        axis.title=element_text(size=16,face="bold"),
        legend.title = element_text( size=16, face="bold"),
        legend.text = element_text(size=14)
        ) + 
  labs(color = "pH") +scale_colour_cmocean() 


```
### CAP Analysis

## CAP Species

```{r, results="hide",warning=FALSE}
#Run CAP analysis to identify predictor species
vare.cap <- capscale(method.rel_abun ~ btl_Ph+btl_T090C+btl_OxsatMm.Kg+Depth_m_notes+btl_Latitude+btl_Longitude+btl_Sal00,  data=method.sampledf, dist="bray")

#Retain species scores
sppscores(vare.cap) <- method.rel_abun

as.data.frame(vegan::scores(vare.cap, display="species")) %>% 
  rownames_to_column(var = "species") %>% 
  as.tibble %>%
 mutate(dist = sqrt((CAP1 - 0)^2 + (CAP2 - 0)^2)) -> vare.cap_species_distances


as.data.frame(vegan::scores(vare.cap, display="bp")) %>% 
  rownames_to_column(var = "env") %>% 
  as.tibble %>%
 mutate(dist = sqrt((CAP1 - 0)^2 + (CAP2 - 0)^2)) -> vare.cap_env_distances


```
##### Check For Break Point for Top Species
```{r}
species_distances <- as.data.frame(vare.cap_species_distances)
TAXcap = tax_table(physeq_obj._CO1_sum.tax_goa) %>% as.data.frame()

species_distances %>% 
  mutate(., sum.taxonomy=species) %>% 
  left_join(TAXcap) -> species_distances

rownames(species_distances) <- species_distances$sum.taxonomy

# Now add the environmental variables as arrows
arrowmat <- species_distances

#Rename row names to clean up plot

species_distances %>% 
  filter(., Species!="NA")-> namers

rownames(namers) <- namers$name


# Add labels, make a data.frame
arrowdf <- data.frame(labels = namers$Species, namers)

arrowdf %>% 
  filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
  arrange(desc(dist)) %>% 
  dplyr::slice(1:100) 

arrowdf %>% 
arrange(desc(dist)) %>% 
    filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
   dplyr::slice(1:10) %>% 
ggplot(., aes(x= reorder(labels, -dist), y=dist)) +
  geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r}
arrowdf %>% 
arrange(desc(dist)) %>% 
    filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
   dplyr::slice(1:10)-> arrowdf


summary(vare.cap)$cont %>% as.data.frame() %>% round(3)-> vare.cap_prop

as.tibble(vare.cap_prop,rownames = "rowname") %>% 
  pivot_longer(., cols=-rowname, values_to = "value", names_to = "name") %>% 
  filter(., rowname=="Proportion Explained") %>% 
  filter(., name %in% c("importance.CAP1","importance.CAP2"))-> vare.cap_prop_tib

# Add labels, make a data.frame
arrowdf_env <- data.frame(labels = vare.cap_env_distances$env, vare.cap_env_distances)

arrowdf_env %>% 
arrange(desc(dist)) %>% 
  mutate(., labels = recode(labels,`btl_Latitude`="Lat",
                            `btl_Longitude`="Lon",
                            `btl_OxsatMm.Kg`="OxsatMm.Kg",
                            `btl_Ph`="pH",
                            `btl_T090C`="˚C",
                            `Depth_m_notes` = "Depth",
                            `btl_Sal00`="PSU",
                            `SeasonSpring`="Season"))-> arrowdf_env

# Define the arrow aesthetic mapping
arrow_map <- aes(xend = 0.3 *CAP1, 
                 yend = 0.3 *CAP2, 
                 x = 0, 
                 y = 0, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels)

arrow_map2 <- aes(xend = 2.3 *CAP1, 
                 yend = 2.3 *CAP2, 
                 x = 0, 
                 y = 0, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels)

label_map <- aes(x = 2.3 * CAP1, 
                 y = 2.3 * CAP2, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels,
                 alpha=0.7,
                 fontface="italic")
label_map2 <- aes(x = 0.27 * CAP1, 
                 y = 0.27 * CAP2, 
                 shape = NULL, 
                 color = NULL, 
                 alpha=0.7,
                 label = labels)

arrowhead = arrow(length = unit(0.02, "npc"))

method.sampledf$sample <- rownames(method.sampledf)
# Plot CAP
as.data.frame(vare.cap$CCA$wa) %>% 
  rownames_to_column(var = "sample") %>% 
  as.tibble() %>% 
  left_join(method.sampledf)-> data_cap


data_cap %>% 
  ggplot(aes(x=CAP1, y=CAP2)) + geom_point(aes(col=btl_Ph), size =3) + geom_segment(
    mapping = arrow_map2, 
    size = .5, 
    data = arrowdf, 
    color = "dodgerblue3", 
    arrow = arrowhead
  ) +
  geom_label(
    mapping = label_map, 
    size = 4,  
        color = "dodgerblue3", 
    data = arrowdf, 
    show.legend = FALSE,
    position=position_jitter(width=0.03,height=0.03)
  ) + 
  geom_segment(
    mapping = arrow_map, 
    size = .5, 
    data = arrowdf_env, 
    color = "grey", 
    arrow = arrowhead
  ) +
  geom_label(
    mapping = label_map2, 
    size = 5, 
    data = arrowdf_env, 
    show.legend = FALSE,
    position=position_jitter(width=0.03,height=0.03)
  )  +
  ylab(paste0("CAP2 [",round(vare.cap_prop_tib$value[2]*100,1),"]%"))   + xlab(paste0("CAP1 [",round(vare.cap_prop_tib$value[1]*100,1),"]%")) +   
  scale_color_gradientn(colours = cmocean('thermal')(256)) + ggpubr::theme_pubr() +labs(colour="pH") + theme(axis.title = element_text(face="bold", size = 16))




```

##  All Surface Bray

```{r}
physeq_obj._CO1_sum.tax_goa <- subset_samples(physeq_obj._CO1_sum.tax_goa, Depth_m_notes < 30)

physeq_obj._CO1_sum.tax_goa <- prune_samples(sample_sums(physeq_obj._CO1_sum.tax_goa) > 0, physeq_obj._CO1_sum.tax_goa)
physeq_obj._CO1_sum.tax_goa = subset_taxa(physeq_obj._CO1_sum.tax_goa, Kingdom!="Bacteria")
physeq_obj._CO1_sum.tax_goa = subset_taxa(physeq_obj._CO1_sum.tax_goa, Kingdom!="Environmental Unknown")

physeq_obj._CO1_sum.tax_goa = subset_samples(physeq_obj._CO1_sum.tax_goa,
                                             !is.na(btl_Ph) & 
                                               !is.na(btl_T090C) & 
                                               !is.na(btl_OxsatMm.Kg) &
                                               !is.na(btl_Latitude)&
                                               !is.na(btl_Longitude) & !is.na(btl_Sal00))

tax_table(physeq_obj._CO1_sum.tax_goa) %>%  as.data.frame()
```


```{r}

#Betadiversity
#Generate Vegan formatted data table
method.sampledf <- data.frame(sample_data(physeq_obj._CO1_sum.tax_goa))
method.rel_abun<- vegan_otu(physeq_obj._CO1_sum.tax_goa)

#Bray dissimilarity matrix
method.d_carn <- vegdist(method.rel_abun, method="bray")

#PERMANOVA: Method+Site

method.adonis_results_goa <- adonis2(method.rel_abun~btl_Ph+btl_T090C+btl_OxsatMm.Kg+Depth_m_notes+btl_Latitude+btl_Longitude+btl_Sal00, data=method.sampledf, by = "terms",na.action =na.exclude)

method.adonis_results_goa

```

```{r}
ord <- ordinate(physeq_obj._CO1_sum.tax_goa, method = "NMDS", distance = ("bray"))
```

### NMDS Temp
```{r}
##Plot_Ordination
plot_ordination(physeq_obj._CO1_sum.tax_goa, ord, "samples",color = "btl_OxsatMm.Kg") +
  ggtitle(paste0("NMDS - Stress ",round(ord$stress,3))) + 
  geom_point(size = 4) + 
  theme_bw()+ 
  theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5,size = 18, face = "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.text=element_text(size=16), 
        axis.title=element_text(size=16,face="bold"),
        legend.title = element_text( size=16, face="bold"),
        legend.text = element_text(size=14)
        ) + 
  labs(color = "O2") +scale_colour_cmocean() 


```
### CAP Analysis

## CAP Species

```{r, results="hide",warning=FALSE}
#Run CAP analysis to identify predictor species
vare.cap <- capscale(method.rel_abun ~ btl_Ph+btl_T090C+btl_OxsatMm.Kg+Depth_m_notes+btl_Latitude+btl_Longitude+btl_Sal00,  data=method.sampledf, dist="bray")

#Retain species scores
sppscores(vare.cap) <- method.rel_abun

as.data.frame(vegan::scores(vare.cap, display="species")) %>% 
  rownames_to_column(var = "species") %>% 
  as.tibble %>%
 mutate(dist = sqrt((CAP1 - 0)^2 + (CAP2 - 0)^2)) -> vare.cap_species_distances


as.data.frame(vegan::scores(vare.cap, display="bp")) %>% 
  rownames_to_column(var = "env") %>% 
  as.tibble %>%
 mutate(dist = sqrt((CAP1 - 0)^2 + (CAP2 - 0)^2)) -> vare.cap_env_distances


```
##### Check For Break Point for Top Species
```{r}
species_distances <- as.data.frame(vare.cap_species_distances)
TAXcap = tax_table(physeq_obj._CO1_sum.tax_goa) %>% as.data.frame()

species_distances %>% 
  mutate(., sum.taxonomy=species) %>% 
  left_join(TAXcap) -> species_distances

rownames(species_distances) <- species_distances$sum.taxonomy

# Now add the environmental variables as arrows
arrowmat <- species_distances

#Rename row names to clean up plot

species_distances %>% 
  filter(., Species!="NA")-> namers

rownames(namers) <- namers$name


# Add labels, make a data.frame
arrowdf <- data.frame(labels = namers$Species, namers)

arrowdf %>% 
  filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
  arrange(desc(dist)) %>% 
  dplyr::slice(1:100) 

arrowdf %>% 
arrange(desc(dist)) %>% 
    filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
   dplyr::slice(1:10) %>% 
ggplot(., aes(x= reorder(labels, -dist), y=dist)) +
  geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r}
arrowdf %>% 
arrange(desc(dist)) %>% 
    filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
   dplyr::slice(1:10)-> arrowdf


summary(vare.cap)$cont %>% as.data.frame() %>% round(3)-> vare.cap_prop

as.tibble(vare.cap_prop,rownames = "rowname") %>% 
  pivot_longer(., cols=-rowname, values_to = "value", names_to = "name") %>% 
  filter(., rowname=="Proportion Explained") %>% 
  filter(., name %in% c("importance.CAP1","importance.CAP2"))-> vare.cap_prop_tib

# Add labels, make a data.frame
arrowdf_env <- data.frame(labels = vare.cap_env_distances$env, vare.cap_env_distances)

arrowdf_env %>% 
arrange(desc(dist)) %>% 
  mutate(., labels = recode(labels,`btl_Latitude`="Lat",
                            `btl_Longitude`="Lon",
                            `btl_OxsatMm.Kg`="OxsatMm.Kg",
                            `btl_Ph`="pH",
                            `btl_T090C`="˚C",
                            `Depth_m_notes` = "Depth",
                            `btl_Sal00`="PSU",
                            `SeasonSpring`="Season"))-> arrowdf_env

# Define the arrow aesthetic mapping
arrow_map <- aes(xend = 0.3 *CAP1, 
                 yend = 0.3 *CAP2, 
                 x = 0, 
                 y = 0, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels)

arrow_map2 <- aes(xend = 2.3 *CAP1, 
                 yend = 2.3 *CAP2, 
                 x = 0, 
                 y = 0, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels)

label_map <- aes(x = 2.3 * CAP1, 
                 y = 2.3 * CAP2, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels,
                 alpha=0.7,
                 fontface="italic")
label_map2 <- aes(x = 0.27 * CAP1, 
                 y = 0.27 * CAP2, 
                 shape = NULL, 
                 color = NULL, 
                 alpha=0.7,
                 label = labels)

arrowhead = arrow(length = unit(0.02, "npc"))

method.sampledf$sample <- rownames(method.sampledf)
# Plot CAP
as.data.frame(vare.cap$CCA$wa) %>% 
  rownames_to_column(var = "sample") %>% 
  as.tibble() %>% 
  left_join(method.sampledf)-> data_cap


data_cap %>% 
  ggplot(aes(x=CAP1, y=CAP2)) + geom_point(aes(col=btl_OxsatMm.Kg), size =3) + geom_segment(
    mapping = arrow_map2, 
    size = .5, 
    data = arrowdf, 
    color = "dodgerblue3", 
    arrow = arrowhead
  ) +
  geom_label(
    mapping = label_map, 
    size = 4,  
        color = "dodgerblue3", 
    data = arrowdf, 
    show.legend = FALSE,
    position=position_jitter(width=0.03,height=0.03)
  ) + 
  geom_segment(
    mapping = arrow_map, 
    size = .5, 
    data = arrowdf_env, 
    color = "grey", 
    arrow = arrowhead
  ) +
  geom_label(
    mapping = label_map2, 
    size = 5, 
    data = arrowdf_env, 
    show.legend = FALSE,
    position=position_jitter(width=0.03,height=0.03)
  )  +
  ylab(paste0("CAP2 [",round(vare.cap_prop_tib$value[2]*100,1),"]%"))   + xlab(paste0("CAP1 [",round(vare.cap_prop_tib$value[1]*100,1),"]%")) +   
  scale_color_gradientn(colours = cmocean('thermal')(256)) + ggpubr::theme_pubr() +labs(colour="O2 Sat") + theme(axis.title = element_text(face="bold", size = 16))




```

##  All subsurface Bray

```{r}
physeq_obj._CO1_sum.tax_goa <- subset_samples(physeq_obj._CO1_sum.tax_goa, Depth_m_notes >30)

physeq_obj._CO1_sum.tax_goa <- prune_samples(sample_sums(physeq_obj._CO1_sum.tax_goa) > 0, physeq_obj._CO1_sum.tax_goa)
physeq_obj._CO1_sum.tax_goa = subset_taxa(physeq_obj._CO1_sum.tax_goa, Kingdom!="Bacteria")
physeq_obj._CO1_sum.tax_goa = subset_taxa(physeq_obj._CO1_sum.tax_goa, Kingdom!="Environmental Unknown")

physeq_obj._CO1_sum.tax_goa = subset_samples(physeq_obj._CO1_sum.tax_goa,
                                             !is.na(btl_Ph) & 
                                               !is.na(btl_T090C) & 
                                               !is.na(btl_OxsatMm.Kg) &
                                               !is.na(btl_Latitude)&
                                               !is.na(btl_Longitude) & !is.na(btl_Sal00))

tax_table(physeq_obj._CO1_sum.tax_goa) %>%  as.data.frame()
```


```{r}

#Betadiversity
#Generate Vegan formatted data table
method.sampledf <- data.frame(sample_data(physeq_obj._CO1_sum.tax_goa))
method.rel_abun<- vegan_otu(physeq_obj._CO1_sum.tax_goa)

#Bray dissimilarity matrix
method.d_carn <- vegdist(method.rel_abun, method="bray")

#PERMANOVA: Method+Site

method.adonis_results_goa <- adonis2(method.rel_abun~btl_Ph+btl_T090C+btl_OxsatMm.Kg+Depth_m_notes+btl_Latitude+btl_Longitude+btl_Sal00, data=method.sampledf, by = "terms",na.action =na.exclude)

method.adonis_results_goa

```

```{r}
ord <- ordinate(physeq_obj._CO1_sum.tax_goa, method = "NMDS", distance = ("bray"))
```

### NMDS Temp
```{r}
##Plot_Ordination
plot_ordination(physeq_obj._CO1_sum.tax_goa, ord, "samples",color = "btl_Ph") +
  ggtitle(paste0("NMDS - Stress ",round(ord$stress,3))) + 
  geom_point(size = 4) + 
  theme_bw()+ 
  theme(plot.title = element_text(hjust = 0.5,size = 20, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5,size = 18, face = "bold"),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.text=element_text(size=16), 
        axis.title=element_text(size=16,face="bold"),
        legend.title = element_text( size=16, face="bold"),
        legend.text = element_text(size=14)
        ) + 
  labs(color = "pH") +scale_colour_cmocean() 


```
### CAP Analysis

## CAP Species

```{r, results="hide",warning=FALSE}
#Run CAP analysis to identify predictor species
vare.cap <- capscale(method.rel_abun ~ btl_Ph+btl_T090C+btl_OxsatMm.Kg+Depth_m_notes+btl_Latitude+btl_Longitude+btl_Sal00,  data=method.sampledf, dist="bray")

#Retain species scores
sppscores(vare.cap) <- method.rel_abun

as.data.frame(vegan::scores(vare.cap, display="species")) %>% 
  rownames_to_column(var = "species") %>% 
  as.tibble %>%
 mutate(dist = sqrt((CAP1 - 0)^2 + (CAP2 - 0)^2)) -> vare.cap_species_distances


as.data.frame(vegan::scores(vare.cap, display="bp")) %>% 
  rownames_to_column(var = "env") %>% 
  as.tibble %>%
 mutate(dist = sqrt((CAP1 - 0)^2 + (CAP2 - 0)^2)) -> vare.cap_env_distances


```
##### Check For Break Point for Top Species
```{r}
species_distances <- as.data.frame(vare.cap_species_distances)
TAXcap = tax_table(physeq_obj._CO1_sum.tax_goa) %>% as.data.frame()

species_distances %>% 
  mutate(., sum.taxonomy=species) %>% 
  left_join(TAXcap) -> species_distances

rownames(species_distances) <- species_distances$sum.taxonomy

# Now add the environmental variables as arrows
arrowmat <- species_distances

#Rename row names to clean up plot

species_distances %>% 
  filter(., Species!="NA")-> namers

rownames(namers) <- namers$name


# Add labels, make a data.frame
arrowdf <- data.frame(labels = namers$Species, namers)

arrowdf %>% 
  filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
  arrange(desc(dist)) %>% 
  dplyr::slice(1:100) 

arrowdf %>% 
arrange(desc(dist)) %>% 
    filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
   dplyr::slice(1:10) %>% 
ggplot(., aes(x= reorder(labels, -dist), y=dist)) +
  geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r}
arrowdf %>% 
arrange(desc(dist)) %>% 
    filter(., !Phylum %in% c("Bacillariophyta","Chlorophyta","Dinophyceae__p","Dictyochophyceae__p","Pelagophyceae__p")) %>% 
   dplyr::slice(1:10)-> arrowdf


summary(vare.cap)$cont %>% as.data.frame() %>% round(3)-> vare.cap_prop

as.tibble(vare.cap_prop,rownames = "rowname") %>% 
  pivot_longer(., cols=-rowname, values_to = "value", names_to = "name") %>% 
  filter(., rowname=="Proportion Explained") %>% 
  filter(., name %in% c("importance.CAP1","importance.CAP2"))-> vare.cap_prop_tib

# Add labels, make a data.frame
arrowdf_env <- data.frame(labels = vare.cap_env_distances$env, vare.cap_env_distances)

arrowdf_env %>% 
arrange(desc(dist)) %>% 
  mutate(., labels = recode(labels,`btl_Latitude`="Lat",
                            `btl_Longitude`="Lon",
                            `btl_OxsatMm.Kg`="OxsatMm.Kg",
                            `btl_Ph`="pH",
                            `btl_T090C`="˚C",
                            `Depth_m_notes` = "Depth",
                            `btl_Sal00`="PSU",
                            `SeasonSpring`="Season"))-> arrowdf_env

# Define the arrow aesthetic mapping
arrow_map <- aes(xend = 0.3 *CAP1, 
                 yend = 0.3 *CAP2, 
                 x = 0, 
                 y = 0, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels)

arrow_map2 <- aes(xend = 2.3 *CAP1, 
                 yend = 2.3 *CAP2, 
                 x = 0, 
                 y = 0, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels)

label_map <- aes(x = 2.3 * CAP1, 
                 y = 2.3 * CAP2, 
                 shape = NULL, 
                 color = NULL, 
                 label = labels,
                 alpha=0.7,
                 fontface="italic")
label_map2 <- aes(x = 0.27 * CAP1, 
                 y = 0.27 * CAP2, 
                 shape = NULL, 
                 color = NULL, 
                 alpha=0.7,
                 label = labels)

arrowhead = arrow(length = unit(0.02, "npc"))

method.sampledf$sample <- rownames(method.sampledf)
# Plot CAP
as.data.frame(vare.cap$CCA$wa) %>% 
  rownames_to_column(var = "sample") %>% 
  as.tibble() %>% 
  left_join(method.sampledf)-> data_cap


data_cap %>% 
  ggplot(aes(x=CAP1, y=CAP2)) + geom_point(aes(col=btl_Ph), size =3) + geom_segment(
    mapping = arrow_map2, 
    size = .5, 
    data = arrowdf, 
    color = "dodgerblue3", 
    arrow = arrowhead
  ) +
  geom_label(
    mapping = label_map, 
    size = 4,  
        color = "dodgerblue3", 
    data = arrowdf, 
    show.legend = FALSE,
    position=position_jitter(width=0.03,height=0.03)
  ) + 
  geom_segment(
    mapping = arrow_map, 
    size = .5, 
    data = arrowdf_env, 
    color = "grey", 
    arrow = arrowhead
  ) +
  geom_label(
    mapping = label_map2, 
    size = 5, 
    data = arrowdf_env, 
    show.legend = FALSE,
    position=position_jitter(width=0.03,height=0.03)
  )  +
  ylab(paste0("CAP2 [",round(vare.cap_prop_tib$value[2]*100,1),"]%"))   + xlab(paste0("CAP1 [",round(vare.cap_prop_tib$value[1]*100,1),"]%")) +   
  scale_color_gradientn(colours = cmocean('thermal')(256)) + ggpubr::theme_pubr() +labs(colour="O2 Sat") + theme(axis.title = element_text(face="bold", size = 16))




```

