---
title: "M2 2023 PPS Spring-Summer Deployment"
author: "Zack Gold"
date: "2024-10-09"
output: html_document
---

# Load Data

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(sf)
library("rnaturalearth")
library("rnaturalearthdata")
library(cmocean)
```
# Machine Readible QAQC

```{r}

sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_M2-PPS-0523.csv"), header=T,fileEncoding="UTF-8")

sample_Data %>% 
   mutate(., Combined_date = str_c(Collection_Date_local, " ",Collection_Time_local),
            Combined_date_local = str_c(Collection_Date_local, " ",Collection_Time_local),
          Date_local_check = as.POSIXct(Combined_date_local, format="%m/%d/%y %H:%M", tz="US/Alaska"),
         Date_local_check = if_else(is.na(Date_local_check), as.POSIXct(Combined_date_local, format="%m/%d/%y", tz="UTC"), Date_local_check )) %>% 
  mutate(.,  Date_local = as.POSIXct(Combined_date, format="%m/%d/%Y %H:%M", tz="US/Alaska"),
         Date_UTC= format(Date_local,tz="UTC")) %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "°"," ")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
      mutate(., Lat_dec=as.numeric(Lat_dec)) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "°"," ")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  mutate(., Cast = str_remove(Cast_No., "Event "),
         Cast = as.integer(Cast), 
         Bottle=NA) -> QAQCMRE_CruiseSampleMetadata_PPS_0523


c("Sample_Name","Biological_Replicate","Technical_Replicate","Negative_control",    "Cruise_ID_short",     "Cruise_ID_long",     "Collection_Date_UTC", "Collection_Date_local","Collection_Time_UTC","Collection_Time_local"                   ,"Field_Sample_Name",   "Cast_No.",  "Rosette_position",    "Field_collection_method"       ,"Preservation",       "Area.within.region",  "Station",    "Depth_m",   
"Lat",        "Lon",        "Sample_volume_ml",   
"Personnel_responsible_for_Collecting_Sample", "Field_Notes","Combined_date",      "Combined_date_local", "Date_UTC",   "Date_local_check",   
"Date_local", "Lat_fix",    "Lat_dec",   
"Lon_fix",    "Lon_dec",    "Cast",      
"Bottle"   ) -> skq1_colnames

colnames(QAQCMRE_CruiseSampleMetadata_PPS_0523)
setdiff(skq1_colnames,colnames(QAQCMRE_CruiseSampleMetadata_PPS_0523) )
setdiff(colnames(QAQCMRE_CruiseSampleMetadata_PPS_0523),skq1_colnames )

QAQCMRE_CruiseSampleMetadata_PPS_0523 <- QAQCMRE_CruiseSampleMetadata_PPS_0523[, skq1_colnames]

readr::write_excel_csv(QAQCMRE_CruiseSampleMetadata_PPS_0523, file="QAQCMRE_CruiseSampleMetadata_PPS_0523.csv")

```

```{r}
QAQCMRE_CruiseSampleMetadata_PPS_0523 %>% 
  filter(., is.na(Lat_dec))
```

```{r}

min_lat <- min(QAQCMRE_CruiseSampleMetadata_PPS_0523$Lat_dec, na.rm = T)
max_lat <- max(QAQCMRE_CruiseSampleMetadata_PPS_0523$Lat_dec, na.rm = T)

min_lon <- min(QAQCMRE_CruiseSampleMetadata_PPS_0523$Lon_dec, na.rm = T)
max_lon <- max(QAQCMRE_CruiseSampleMetadata_PPS_0523$Lon_dec, na.rm = T)

world <- ne_countries(scale = "medium", returnclass = "sf")
QAQCMRE_CruiseSampleMetadata_PPS_0523$Date_UTC %>% as.Date() -> dates

ggplot(data = world) +
    geom_sf() +
    geom_point(data = QAQCMRE_CruiseSampleMetadata_PPS_0523, aes(x = Lon_dec, y = Lat_dec, colour=as.Date(Date_UTC)), size=2) +
    coord_sf(xlim = c(min_lon-1, max_lon+1), ylim = c(min_lat-1, max_lat+1), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +
  geom_text(data = QAQCMRE_CruiseSampleMetadata_PPS_0523, aes(x = Lon_dec, y = Lat_dec, label=Station),size = 2, colour="black") + scale_color_cmocean(labels=dates, breaks=dates, name ="tempo", start = 0.1, end=0.5) +labs(colour="Date")
```

```{r}
QAQCMRE_CruiseSampleMetadata_PPS_0523 %>% 
  ggplot() +
  geom_point(aes(y = Lat_dec, x =as.Date(Date_UTC), colour=as.Date(Date_UTC)), size=2) + scale_color_cmocean(labels=dates, breaks=dates, name ="tempo", start = 0.1, end=0.5) +labs(colour="Date") +scale_x_date(date_labels = "%b %d %Y")
```

# Read PPS Data

```{r}
PPS_event_header_1 <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 1, skip = 32, sep="|",stringsAsFactors = FALSE)
PPS_event_header_2 <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 1, skip = 35, sep="|",stringsAsFactors = FALSE)

PPS_event_header_1 %>% 
  slice(1) %>% 
  unlist(., use.names=FALSE) -> PPS_event_header_1_list_1

PPS_event_header_2 %>% 
  slice(1) %>% 
  unlist(., use.names=FALSE) -> PPS_event_header_2_list_2

c(PPS_event_header_1_list_1,PPS_event_header_2_list_2) -> pps_event_header

str_trim(pps_event_header) %>% discard(., is.na)  -> pps_event_header_clean
c("Cast",pps_event_header_clean) -> pps_event_header_clean
pps_event_header_clean[length(pps_event_header_clean)] <- "Vol2"

PPS_event_data <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 23, skip = 36,stringsAsFactors = FALSE)

PPS_event_data %>% 
  mutate(., V2= str_remove(V2,":"),
          V5= str_remove(V5,"\\|"),
          V6= str_remove(V6,"\\|"),
          V8= str_remove(V8,"\\|")) %>% dplyr::select(-V1) -> PPS_event_data
  

colnames(PPS_event_data) <- c(pps_event_header_clean)


PPS_event_data %>% 
  rename(Date_PPS_event = Flush) %>% 
  mutate(., Cast=as.integer(Cast))-> PPS_event_data

```

```{r}
PPS_deployment_header_1 <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 1, skip = 71, sep="|",stringsAsFactors = FALSE)
PPS_deployment_header_2 <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 1, skip = 72, sep="|",stringsAsFactors = FALSE)

PPS_deployment_header_1 %>% 
  slice(1) %>% 
  unlist(., use.names=FALSE) -> PPS_deployment_header_1_list_1

PPS_deployment_header_2 %>% 
  slice(1) %>% 
  unlist(., use.names=FALSE) -> PPS_deployment_header_2_list_2

c(PPS_deployment_header_1_list_1,PPS_deployment_header_2_list_2) -> pps_deployment_header

str_trim(pps_deployment_header) %>% discard(., is.na)  -> pps_deployment_header_clean
pps_deployment_header_clean[(length(pps_deployment_header_clean)-7):length(pps_deployment_header_clean)] -> pps_deployment_header_clean2

PPS_deployment_data <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 91, skip = 74,sep="|")

PPS_deployment_data %>% 
  filter(., !is.na(V1)) -> PPS_deployment_data

colnames(PPS_deployment_data) <- c(pps_deployment_header_clean2)

PPS_deployment_data %>% 
  rename(Cast=Number) %>% 
  mutate(., Time=str_trim(Time)) %>% 
  separate(Time , into =c("Date_PPS_deployment","Deployment_Sample_Time"), sep=" ") -> PPS_deployment_data

PPS_deployment_data %>% 
  mutate(.,  Procedure=str_trim(Procedure),
         Procedure=str_replace(Procedure," ","_")
        ) %>% 
  pivot_wider(names_from = Procedure, values_from = c(Date_PPS_deployment,Deployment_Sample_Time,`Temp.`,`Voltage`, Pumped,Duration,Result), names_glue = "{Procedure}:{.value}") -> PPS_deployment_data

```

```{r}
PPS_pumping_period <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 1, skip = 184, sep="|",stringsAsFactors = FALSE)
PPS_pumping_period

PPS_pumping_header_1 <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 1, skip = 188,stringsAsFactors = FALSE, sep="]",comment.char = "")
PPS_pumping_header_1

PPS_pumping_header_1 %>% 
  slice(1) %>% 
  unlist(., use.names=FALSE) -> PPS_pumping_header_1_list_1

str_trim(PPS_pumping_header_1_list_1) %>% discard(., is.na) %>% 
  str_replace(., "\\[","") %>% str_replace(., "\\#","") %>% 
  str_replace(., " ","_")-> pps_pumping_header_clean

PPS_pumping_data <- read.table(file = here("PPS_Offload_M2_2023_14965-01.txt"), header=F, nrows = 1421, skip = 190)

colnames(PPS_pumping_data) <- c(pps_pumping_header_clean)
PPS_pumping_data %>% 
  rename(Cast=event) -> PPS_pumping_data

PPS_event_data %>% 
  left_join(PPS_deployment_data) %>% 
   rename_with(.fn = ~ paste0("PPS_", .x)) -> PPS_data_to_append
```

# Merge Sample and PPS Data


```{r}
 QAQCMRE_CruiseSampleMetadata_PPS_0523 %>% 
  left_join(PPS_data_to_append, by=c("Cast" = "PPS_Cast") ) %>% 
    mutate(., Combined_PPS_date = str_c(PPS_Date_PPS_event, " ",`PPS_Sample Time`)) -> PPS_2023_M2_Spring_Summer_sample_data


#colnames(PPS_data_to_append)[2:28] -> cols_2_keep

library(rlang)

PPS_2023_M2_Spring_Summer_sample_data %>%
  mutate(., verbatimCoordinateSystem = case_when(!is.na(Lon) & !is.na(Lat) ~ "degrees minutes seconds", TRUE ~ NA_character_)) %>%
  select(Sample_Name, 
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Station,
         Depth_m_notes=Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         verbatimEventDate = Collection_Date_local,
         verbatimEventTime = Collection_Time_local,
         verbatimLongitude = Lon,
         verbatimLatitude = Lat,
         verbatimCoordinateSystem,
         #!!!syms(cols_2_keep),
                             starts_with("ctd"),
        starts_with("btl")
         ) -> PPS_2023_M2_Spring_Summer_sample_data

readr::write_excel_csv(PPS_2023_M2_Spring_Summer_sample_data, file="FinalOME_Merge_M2-PPS-0523.csv")


```

