---
title: "DY2306 2023 EcoFOCI Spring Mooring Cruise"
author: "Zack Gold"
date: "2024-10-08"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)

```

```{r}
ctd_Data <- read.csv(file = here("CTD_raw_BottleFile_DY23-06.csv"), header=T)

sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_DY23-06.csv"), header=T,fileEncoding="UTF-8")

```

```{r}
ctd_Data %>% 
  mutate(., holder1 = str_remove(profile_id,"DY2306c"),
         Cast = str_remove(holder1,"_btl")) %>% 
           mutate(., Cast = as.numeric(Cast)) -> ctd_Data

ctd_Data$Cast <- as.character(ctd_Data$Cast)
ctd_Data$bottle <- as.character(ctd_Data$bottle)
```


```{r}
sample_Data %>% 
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%Y %H:%M", tz="UTC"),
                     Date_UTC = if_else(is.na(Date_UTC), as.POSIXct(Collection_Date_UTC, format="%m/%d/%y", tz="UTC"), Date_UTC ), 
         Date_local= format(Date_UTC,tz="US/Alaska")) %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "°"," ")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "°"," ")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  mutate(., Cast_No.=as.character(Cast_No.),
         Rosette_position=as.character(Rosette_position)) %>% 
  left_join(ctd_Data, by=c("Cast_No."="Cast","Rosette_position"="bottle")) %>% 
  mutate(., Date_UTC_btl = as.POSIXct(`time..UTC.`, format="%Y-%m-%dT%H:%M:%SZ", tz="UTC") )-> EcoFOCI_Spring_2023_sample_data


colnames(ctd_Data)[2:13] -> cols_2_keep
library(rlang)

EcoFOCI_Spring_2023_sample_data %>% 
  select(Sample_Name, 
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Area.within.region,
         Station,
         Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         Latitude=`latitude..degrees_north.`, 
         Longitude=`longitude..degrees_east.`,
          Date_UTC_btl,
         !!!syms(cols_2_keep)) -> EcoFOCI_Spring_2023_sample_data

readr::write_excel_csv(EcoFOCI_Spring_2023_sample_data, file="FinalOME_Merge_DY23-06.csv")
```