---
title: "Sikuliaq Data Conversion"
author: "Zack Gold"
date: "2024-12-23"
output: html_document
---

# Load Data

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(oce)
library(readxl)
library(sf)
library("rnaturalearth")
library("rnaturalearthdata")
library(cmocean)

```

# Machine Readible QAQC

```{r}

sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_SKQ23-12S.csv"), header=T,fileEncoding="UTF-8")

sample_Data %>% 
  mutate(., Sample_Name=str_replace(Sample_Name,"-","_")) %>% 
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC),
          Combined_date_local = str_c(Collection_Date_local, " ",Collection_Time_local),
          Date_local_check = as.POSIXct(Combined_date_local, format="%m/%d/%y %H:%M", tz="US/Alaska"),
         Date_local_check = if_else(is.na(Date_local_check), as.POSIXct(Combined_date_local, format="%m/%d/%y", tz="UTC"), Date_local_check )) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%Y %H:%M", tz="UTC"),
                         Date_UTC = if_else(is.na(Date_UTC), as.POSIXct(Collection_Date_UTC, format="%m/%d/%y", tz="UTC"), Date_UTC ), 
         Date_local= format(Date_UTC,tz="US/Alaska")) %>% 
 mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "° "," "),
          Lat_fix=str_trim(Lat_fix) ) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
          mutate(., Lat_dec=as.numeric(Lat_dec)) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "° "," ")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  mutate(., Cast= str_remove(Cast_No., "CTD"),
         Cast= as.numeric(Cast),
         Cast=as.character(Cast),
         Bottle=as.character(Rosette_position)) -> QAQCMRE_CruiseSampleMetadata_SKQ23_12S


c("Sample_Name","Biological_Replicate","Technical_Replicate","Negative_control",    "Cruise_ID_short",     "Cruise_ID_long",     "Collection_Date_UTC", "Collection_Date_local","Collection_Time_UTC","Collection_Time_local"                   ,"Field_Sample_Name",   "Cast_No.",  "Rosette_position",    "Field_collection_method"       ,"Preservation",       "Area.within.region",  "Station",    "Depth_m",   
"Lat",        "Lon",        "Sample_volume_ml",   
"Personnel_responsible_for_Collecting_Sample", "Field_Notes","Combined_date",      "Combined_date_local", "Date_UTC",   "Date_local_check",   
"Date_local", "Lat_fix",    "Lat_dec",   
"Lon_fix",    "Lon_dec",    "Cast",      
"Bottle"   ) -> skq1_colnames

colnames(QAQCMRE_CruiseSampleMetadata_SKQ23_12S)
setdiff(skq1_colnames,colnames(QAQCMRE_CruiseSampleMetadata_SKQ23_12S) )
setdiff(colnames(QAQCMRE_CruiseSampleMetadata_SKQ23_12S),skq1_colnames )

QAQCMRE_CruiseSampleMetadata_SKQ23_12S <- QAQCMRE_CruiseSampleMetadata_SKQ23_12S[, skq1_colnames]

readr::write_excel_csv(QAQCMRE_CruiseSampleMetadata_SKQ23_12S, file="QAQCMRE_CruiseSampleMetadata_SKQ23_12S.csv")



```



```{r}

min_lat <- min(QAQCMRE_CruiseSampleMetadata_SKQ23_12S$Lat_dec, na.rm = T)
max_lat <- max(QAQCMRE_CruiseSampleMetadata_SKQ23_12S$Lat_dec, na.rm = T)

min_lon <- min(QAQCMRE_CruiseSampleMetadata_SKQ23_12S$Lon_dec, na.rm = T)
max_lon <- max(QAQCMRE_CruiseSampleMetadata_SKQ23_12S$Lon_dec, na.rm = T)

world <- ne_countries(scale = "medium", returnclass = "sf")
QAQCMRE_CruiseSampleMetadata_SKQ23_12S$Date_UTC %>% as.Date() -> dates


ggplot(data = world) +
    geom_sf() +
    geom_point(data = QAQCMRE_CruiseSampleMetadata_SKQ23_12S, aes(x = Lon_dec, y = Lat_dec, colour=as.Date(Date_UTC)), size=2) +
    coord_sf(xlim = c(min_lon-1, max_lon+1), ylim = c(min_lat-1, max_lat+1), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +
  geom_text(data = QAQCMRE_CruiseSampleMetadata_SKQ23_12S, aes(x = Lon_dec, y = Lat_dec, label=Station),size = 2, colour="black") + scale_color_cmocean(labels=dates, breaks=dates, name ="tempo", start = 0.1, end=0.5) +labs(colour="Date")


```

```{r}
QAQCMRE_CruiseSampleMetadata_SKQ23_12S %>% 
  filter(., is.na(Lat_dec))
```
```{r}
QAQCMRE_CruiseSampleMetadata_SKQ23_12S %>% 
  ggplot() +
  geom_point(aes(y = Lat_dec, x =as.Date(Date_UTC), colour=as.Date(Date_UTC)), size=2) + scale_color_cmocean(labels=dates, breaks=dates, name ="tempo", start = 0.1, end=0.5) +labs(colour="Date") +scale_x_date(date_labels = "%b %d %Y")

```
# Read Bottle Data

```{r}
### Identify the list in the directory
files = dir(path = here("CTD_raw_BottleFile_SKQ23-12S","proc"), pattern = ".btl", full.names = TRUE )

## preallocate the container to store the individual 
bottle = list()

### Loop the CNV file and create a list of casted CTD
for (i in 1:length(files)){
  
bottle[[i]]  = read.ctd.sbe(files[i], btl = T)
}
```

```{r}
str_remove(files, "/Users/zgold/Documents/PMEL/Science/EcoFOCI/data/1_SampleCollection/2023_SikuliaqDBO_CruiseData/CTD_raw_BottleFile_SKQ23-12S/proc/") %>% 
  str_remove(., ".btl") -> cast_names

datalist = vector("list", length = length(cast_names))

for (i in 1:length(files)){
  
datalist[[i]] = bottle[[i]]@data%>%
  as_data_frame() %>% 
  mutate(., Cast= cast_names[i])
}

bottle_Data = do.call(rbind, datalist)
```

```{r}
bottle_Data %>% 
  mutate(.,
         Cast = str_remove(Cast,"skq202312s_")) %>% 
           mutate(., Cast = as.numeric(Cast)) %>% 
   rename_with(.fn = ~ paste0("btl_", .x)) -> bottle_Data

bottle_Data$Cast <- as.character(bottle_Data$btl_Cast)
bottle_Data$bottle <- as.character(bottle_Data$btl_Bottle)
```

# Read CTD Downcast Data

```{r}

ctd_Data <- read.csv(file =here("CTD_skq202312s_final_merged_3eeb_9b4e_d51f.csv"), header=T)

ctd_Data %>% 
  dplyr::group_by(profile_id,pressure)  %>% 
  filter(n()>1) -> duplicate_bottles

duplicate_bottles %>% 
     dplyr::group_by(profile_id,pressure) %>% 
       mutate(BTLID = paste0(BTLID, collapse = ";")) %>% 
  dplyr::select(., profile_id,pressure,BTLID, `SI..uM.l.`,`PO4..uM.l.`,`NO2..uM.l.`,`NO3..uM.l.`,`NH4..uM.l.`) %>% 
   dplyr::group_by(profile_id,pressure,BTLID) %>% 
  dplyr::summarise(across(where(is.numeric), mean)) -> bottles_avg

duplicate_bottles %>% 
  dplyr::select(-`SI..uM.l.`,-`PO4..uM.l.`,-`NO2..uM.l.`,-`NO3..uM.l.`,-`NH4..uM.l.`, -BTLID) %>% 
  distinct() %>% 
  left_join(bottles_avg) -> duplicate_bottles_c


ctd_Data %>% 
  mutate(.,BTLID =as.character(BTLID) ) %>% 
  filter(., !profile_id %in% duplicate_bottles_c$profile_id) %>% 
  bind_rows(duplicate_bottles_c) %>% 
  mutate(., holder1 = str_remove(profile_id,"skq202312sc"),
          Cast = as.numeric(holder1)) %>% 
   rename_with(.fn = ~ paste0("ctd_", .x)) -> ctd_Data


ctd_Data$Cast <- as.character(ctd_Data$ctd_Cast)
ctd_Data$pressure <- as.numeric(ctd_Data$ctd_pressure)

```


# Merge Sample, Bottle, and CTD Data

```{r}
QAQCMRE_CruiseSampleMetadata_SKQ23_12S %>% 
  mutate(pressure= round(Depth_m,0)) %>% 
    left_join(ctd_Data, by = c("Cast" = "Cast", "pressure" = "pressure")) %>% 
  left_join(bottle_Data, by = c("Cast" = "Cast", "Bottle" = "bottle")) %>%
  mutate(., Date_UTC_btl = as.POSIXct(`btl_time`, format="%Y-%m-%d %H:%M:%S", tz="UTC") ) -> SikuliaqDBO_2023_Cruise_sample_data


#colnames(ctd_Data)[2:39] -> cols_2_keep
library(rlang)

SikuliaqDBO_2023_Cruise_sample_data %>% 
  mutate(., verbatimCoordinateSystem = case_when(!is.na(Lon) & !is.na(Lat) ~ "degrees minutes seconds", TRUE ~ NA_character_)) %>%
  select(Sample_Name, 
         Bottle,
         btl_Bottle,
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Station,
         Depth_m_notes=Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         verbatimEventDate = Collection_Date_local,
         verbatimEventTime = Collection_Time_local,
         verbatimLongitude = Lon,
         verbatimLatitude = Lat,
         verbatimCoordinateSystem,
         Area.within.region,
          Date_UTC_btl,
        # !!!syms(cols_2_keep),
           starts_with("ctd"),
        starts_with("btl")
        ) -> SikuliaqDBO_2023_Cruise_sample_data

readr::write_excel_csv(SikuliaqDBO_2023_Cruise_sample_data, file="FinalOME_Merge_SKQ23-12S.csv")
```


