---
title: "Sikuliaq Data Conversion"
author: "Zack Gold"
date: "2024-10-10"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(oce)
library(readxl)

```

```{r}
### Identify the list in the directory
files = dir(path = here("CTD_raw_BottleFile_SKQ23-12S","proc"), pattern = ".btl", full.names = TRUE )

## preallocate the container to store the individual 
ctd = list()

### Loop the CNV file and create a list of casted CTD
for (i in 1:length(files)){
  
ctd[[i]]  = read.ctd.sbe(files[i], btl = T)
}
```

```{r}

str_remove(files, "/Users/zgold/Documents/PMEL/Science/EcoFOCI/data/1_SampleCollection/2023_SikuliaqDBO_CruiseData/CTD_raw_BottleFile_SKQ23-12S/proc/") %>% 
  str_remove(., ".btl") -> cast_names

datalist = vector("list", length = length(cast_names))

for (i in 1:length(files)){
  
datalist[[i]] = ctd[[i]]@data%>%
  as_data_frame() %>% 
  mutate(., Cast= cast_names[i])
}

ctd_Data = do.call(rbind, datalist)
```


```{r}

sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_SKQ23-12S.csv"), header=T,fileEncoding="UTF-8")

```

```{r}
ctd_Data %>% 
  mutate(.,
         Cast = str_remove(Cast,"skq202312s_")) %>% 
           mutate(., Cast = as.numeric(Cast)) -> ctd_Data

ctd_Data$Cast <- as.character(ctd_Data$Cast)
ctd_Data$bottle <- as.character(ctd_Data$Bottle)

ctd_Data %>% 
  filter(., Cast=="63")
ctd_Data$Cast %>%  unique()
```

```{r}

sample_Data %>% 
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%Y %H:%M", tz="UTC"),
                         Date_UTC = if_else(is.na(Date_UTC), as.POSIXct(Collection_Date_UTC, format="%m/%d/%y", tz="UTC"), Date_UTC ), 
         Date_local= format(Date_UTC,tz="US/Alaska")) %>% 
 mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "° "," "),
          Lat_fix=str_trim(Lat_fix) ) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "° "," ")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  mutate(., Cast_No.= str_remove(Cast_No., "CTD"),
         Cast_No.= as.numeric(Cast_No.),
         Cast_No.=as.character(Cast_No.),
         Rosette_position=as.character(Rosette_position)) %>% 
  left_join(ctd_Data, by=c("Cast_No."="Cast","Rosette_position"="bottle")) %>% 
  mutate(., Date_UTC_btl = as.POSIXct(`time`, format="%Y-%m-%d %H:%M:%S", tz="UTC") ) -> SikuliaqDBO_2023_Cruise_sample_data



colnames(ctd_Data)[2:39] -> cols_2_keep
library(rlang)

SikuliaqDBO_2023_Cruise_sample_data %>% 
  select(Sample_Name, 
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Area.within.region,
         Station,
         Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         Latitude, 
         Longitude,
          Date_UTC_btl,
         !!!syms(cols_2_keep)) -> SikuliaqDBO_2023_Cruise_sample_data

readr::write_excel_csv(SikuliaqDBO_2023_Cruise_sample_data, file="FinalOME_Merge_SKQ23-12S.csv")
```


