---
title: "Arctic Metadata Merging"
author: "Zack Gold"
date: "2024-07-01"
output: html_document
---

```{r}
library(tidyverse)
library(here)

```

```{r}
example_final_Data <- read.table(file = here("example_sample_metadata_forR.txt"), header=T,sep="\t")

```

# Load Data
```{r}

FinalOME_Merge_DY20_12 <- read.csv(file = here("data","1_SampleCollection","2020_Dyson_CruiseData","2020_Dyson_CruiseData","FinalOME_Merge_DY20-12.csv"), header=T) %>% rename(salinity_ch1=Sal00,salinity_ch2=Sal11 )

FinalOME_Merge_NO20_01 <-  read.csv(here("data","1_SampleCollection","2020_Norseman_CruiseData","FinalOME_Merge_NO20-01.csv"), header=T) %>% rename(salinity_ch1=Salinity.psu. , T090C=Temperature.deg.C.)


FinalOME_Merge_SKQ21_12S <- read.csv(file = here("data","1_SampleCollection","2021_SikuliaqDBO_CruiseData","2021_SikuliaqDBO_CruiseData","FinalOME_Merge_SKQ21-12S.csv"), header=T) %>% rename( T090C=temperature_ch1,T190C=temperature_ch2)


FinalOME_Merge_DY22_09 <- read.csv(here("data","1_SampleCollection","2022_EcoFociFallMooring_CruiseData","FinalOME_Merge_DY22-09.csv"), header=T) %>% rename(salinity_ch1=salinity_ch1..PSU.,salinity_ch2=	salinity_ch2..PSU. ) %>% rename( T090C=temperature_ch1..degree_C.,T190C=temperature_ch2..degree_C.)

FinalOME_Merge_DY22_06 <- read.csv(here("data","1_SampleCollection","2022_EcoFociSpringMooring_CruiseData","FinalOME_Merge_DY22-06.csv"), header=T) %>% rename(salinity_ch1=salinity_ch1..PSU.,salinity_ch2=	salinity_ch2..PSU. ) %>% rename( T090C=temperature_ch1..degree_C.,T190C=temperature_ch2..degree_C.)

FinalOME_Merge_RC0083 <- read.csv(here("data","1_SampleCollection","2022_GOA-OA_CruiseData","FinalOME_Merge_RC0083.csv"), header=T) %>% rename(salinity_ch1=Sal00 )

FinalOME_Merge_DY23_06 <- read.csv(here("data","1_SampleCollection","2023_EcoFociSpringMooring_CruiseData","FinalOME_Merge_DY23-06.csv"), header=T) %>% rename(salinity_ch1=salinity_ch1..PSU.,salinity_ch2=	salinity_ch2..PSU. ) %>% rename( T090C=temperature_ch1..degree_C.,T190C=temperature_ch2..degree_C.)

FinalOME_Merge_M2_PPS_0523 <- read.csv(here("data","1_SampleCollection","2023_M2_Spring-Summer_CruiseData","FinalOME_Merge_M2-PPS-0523.csv"), header=T)

FinalOME_Merge_SKQ23_12S <- read.csv(here("data","1_SampleCollection","2023_SikuliaqDBO_CruiseData","FinalOME_Merge_SKQ23-12S.csv"), header=T) %>% rename(salinity_ch1=Sal00,salinity_ch2=Sal11 )

```


```{r}

c(colnames(FinalOME_Merge_DY20_12), 
  colnames(FinalOME_Merge_NO20_01),
  colnames(FinalOME_Merge_SKQ21_12S),
  colnames(FinalOME_Merge_DY22_09), 
  colnames(FinalOME_Merge_DY22_06), 
  colnames(FinalOME_Merge_RC0083), 
  colnames(FinalOME_Merge_DY23_06), 
  colnames(FinalOME_Merge_M2_PPS_0523), 
  colnames(FinalOME_Merge_SKQ23_12S)) %>% unique() -> all_unique
```

#Check Salt
```{r}
all_unique %>%  as.tibble() %>% 
  mutate(., SKQ21 = if_else(value %in% colnames(FinalOME_Merge_SKQ21_12S), value, NA),
         DY2020 = if_else(value %in% colnames(FinalOME_Merge_DY20_12), value, NA),
         DY2206_long = if_else(value %in% colnames(FinalOME_Merge_DY22_06), value, NA),
         DY2209_long = if_else(value %in% colnames(FinalOME_Merge_DY22_09), value, NA),
         Norseman2020_long = if_else(value %in% colnames(FinalOME_Merge_NO20_01), value, NA),
         RCGOA2022_long = if_else(value %in% colnames(FinalOME_Merge_RC0083), value, NA),
         M2_PPS_0523 = if_else(value %in% colnames(FinalOME_Merge_M2_PPS_0523), value, NA),
         DY23_06 = if_else(value %in% colnames(FinalOME_Merge_DY23_06), value, NA),
         SKQ202312S_long = if_else(value %in% colnames(FinalOME_Merge_SKQ23_12S), value, NA) ) %>% 
  filter(., str_detect(value,"Sal"))


all_unique %>%  as.tibble() %>% 
  mutate(., SKQ21 = if_else(value %in% colnames(FinalOME_Merge_SKQ21_12S), value, NA),
         DY2020 = if_else(value %in% colnames(FinalOME_Merge_DY20_12), value, NA),
         DY2206_long = if_else(value %in% colnames(FinalOME_Merge_DY22_06), value, NA),
         DY2209_long = if_else(value %in% colnames(FinalOME_Merge_DY22_09), value, NA),
         Norseman2020_long = if_else(value %in% colnames(FinalOME_Merge_NO20_01), value, NA),
         RCGOA2022_long = if_else(value %in% colnames(FinalOME_Merge_RC0083), value, NA),
         M2_PPS_0523 = if_else(value %in% colnames(FinalOME_Merge_M2_PPS_0523), value, NA),
         DY23_06 = if_else(value %in% colnames(FinalOME_Merge_DY23_06), value, NA),
         SKQ202312S_long = if_else(value %in% colnames(FinalOME_Merge_SKQ23_12S), value, NA) ) %>% 
  filter(., str_detect(value,"sal"))

```


#Check Temp
```{r}
all_unique %>%  as.tibble() %>% 
  mutate(., SKQ21 = if_else(value %in% colnames(FinalOME_Merge_SKQ21_12S), value, NA),
         DY2020 = if_else(value %in% colnames(FinalOME_Merge_DY20_12), value, NA),
         DY2206_long = if_else(value %in% colnames(FinalOME_Merge_DY22_06), value, NA),
         DY2209_long = if_else(value %in% colnames(FinalOME_Merge_DY22_09), value, NA),
         Norseman2020_long = if_else(value %in% colnames(FinalOME_Merge_NO20_01), value, NA),
         RCGOA2022_long = if_else(value %in% colnames(FinalOME_Merge_RC0083), value, NA),
         M2_PPS_0523 = if_else(value %in% colnames(FinalOME_Merge_M2_PPS_0523), value, NA),
         DY23_06 = if_else(value %in% colnames(FinalOME_Merge_DY23_06), value, NA),
         SKQ202312S_long = if_else(value %in% colnames(FinalOME_Merge_SKQ23_12S), value, NA) ) %>% 
  filter(., str_detect(value,"temp"))


all_unique %>%  as.tibble() %>% 
  mutate(., SKQ21 = if_else(value %in% colnames(FinalOME_Merge_SKQ21_12S), value, NA),
         DY2020 = if_else(value %in% colnames(FinalOME_Merge_DY20_12), value, NA),
         DY2206_long = if_else(value %in% colnames(FinalOME_Merge_DY22_06), value, NA),
         DY2209_long = if_else(value %in% colnames(FinalOME_Merge_DY22_09), value, NA),
         Norseman2020_long = if_else(value %in% colnames(FinalOME_Merge_NO20_01), value, NA),
         RCGOA2022_long = if_else(value %in% colnames(FinalOME_Merge_RC0083), value, NA),
         M2_PPS_0523 = if_else(value %in% colnames(FinalOME_Merge_M2_PPS_0523), value, NA),
         DY23_06 = if_else(value %in% colnames(FinalOME_Merge_DY23_06), value, NA),
         SKQ202312S_long = if_else(value %in% colnames(FinalOME_Merge_SKQ23_12S), value, NA) ) %>% 
  filter(., str_detect(value,"Temp"))


all_unique %>%  as.tibble() %>% 
  mutate(., SKQ21 = if_else(value %in% colnames(FinalOME_Merge_SKQ21_12S), value, NA),
         DY2020 = if_else(value %in% colnames(FinalOME_Merge_DY20_12), value, NA),
         DY2206_long = if_else(value %in% colnames(FinalOME_Merge_DY22_06), value, NA),
         DY2209_long = if_else(value %in% colnames(FinalOME_Merge_DY22_09), value, NA),
         Norseman2020_long = if_else(value %in% colnames(FinalOME_Merge_NO20_01), value, NA),
         RCGOA2022_long = if_else(value %in% colnames(FinalOME_Merge_RC0083), value, NA),
         M2_PPS_0523 = if_else(value %in% colnames(FinalOME_Merge_M2_PPS_0523), value, NA),
         DY23_06 = if_else(value %in% colnames(FinalOME_Merge_DY23_06), value, NA),
         SKQ202312S_long = if_else(value %in% colnames(FinalOME_Merge_SKQ23_12S), value, NA) ) %>% 
  filter(., str_detect(value,"90C"))

```

# Check Ox
```{r}
all_unique %>%  as.tibble() %>% 
  mutate(., SKQ21 = if_else(value %in% colnames(FinalOME_Merge_SKQ21_12S), value, NA),
         DY2020 = if_else(value %in% colnames(FinalOME_Merge_DY20_12), value, NA),
         DY2206_long = if_else(value %in% colnames(FinalOME_Merge_DY22_06), value, NA),
         DY2209_long = if_else(value %in% colnames(FinalOME_Merge_DY22_09), value, NA),
         Norseman2020_long = if_else(value %in% colnames(FinalOME_Merge_NO20_01), value, NA),
         RCGOA2022_long = if_else(value %in% colnames(FinalOME_Merge_RC0083), value, NA),
         M2_PPS_0523 = if_else(value %in% colnames(FinalOME_Merge_M2_PPS_0523), value, NA),
         DY23_06 = if_else(value %in% colnames(FinalOME_Merge_DY23_06), value, NA),
         SKQ202312S_long = if_else(value %in% colnames(FinalOME_Merge_SKQ23_12S), value, NA) ) %>% 
  filter(., str_detect(value,"ox"))


all_unique %>%  as.tibble() %>% 
  mutate(., SKQ21 = if_else(value %in% colnames(FinalOME_Merge_SKQ21_12S), value, NA),
         DY2020 = if_else(value %in% colnames(FinalOME_Merge_DY20_12), value, NA),
         DY2206_long = if_else(value %in% colnames(FinalOME_Merge_DY22_06), value, NA),
         DY2209_long = if_else(value %in% colnames(FinalOME_Merge_DY22_09), value, NA),
         Norseman2020_long = if_else(value %in% colnames(FinalOME_Merge_NO20_01), value, NA),
         RCGOA2022_long = if_else(value %in% colnames(FinalOME_Merge_RC0083), value, NA),
         M2_PPS_0523 = if_else(value %in% colnames(FinalOME_Merge_M2_PPS_0523), value, NA),
         DY23_06 = if_else(value %in% colnames(FinalOME_Merge_DY23_06), value, NA),
         SKQ202312S_long = if_else(value %in% colnames(FinalOME_Merge_SKQ23_12S), value, NA) ) %>% 
  filter(., str_detect(value,"Ox"))

```