---
title: "Norseman II 2020 Merge CTD + Sample Data"
author: "Zack Gold"
date: "2024-07-03"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(readxl)
```

```{r}
ctd_Data <- read_excel(here("CTD_raw_BottleFile_NO20-01.xlsx"))

sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_NO20-01.csv"), header=T,fileEncoding="UTF-8")

```

```{r}

ctd_Data %>% 
 mutate(., Combined_date = str_c(Month, "/",Day,"/",Year," ",Hours,":",Minutes,":",Seconds)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%Y %H:%M:%S", tz="UTC"),
                  Date_UTC = if_else(is.na(Date_UTC), as.POSIXct(Combined_date, format="%m/%d/%y", tz="UTC"), Date_UTC ), 
         Date_local= format(Date_UTC,tz="US/Alaska")) -> ctd_Data
  
```



```{r}
sample_Data %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "˚","")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "˚","")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  left_join(ctd_Data, by=c("Cast_No."="Consecutive Cast Number","Rosette_position"="Bottle")) -> NO2020_sample_data

setdiff(colnames(ctd_Data),c("Consecutive Cast Number","Bottle","Month","Day","Year","Hours","Minutes","Seconds","Combined_date","Date_local")) -> cols_2_keep

library(rlang)

NO2020_sample_data %>% 
  select(Sample_Name, 
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Area.within.region,
         Station,
         Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         Date_UTC_btl=Date_UTC, 
         !!!syms(cols_2_keep)) -> NO2020_sample_data

readr::write_excel_csv(NO2020_sample_data, file="FinalOME_Merge_NO20-01.csv")
```

