---
title: "Merge Dyson CTD + Sample Data"
author: "Zack Gold"
date: "2024-06-20"
output: html_document
---
```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)

```
```{r}
ctd_Data <- read.csv(file = here("CTD_raw_BottleFile_DY20-12.csv"), header=T)
sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_DY20-12.csv"), header=T,fileEncoding="UTF-8")
example_final_Data <- read.table(file = here("example_sample_metadata_forR.txt"), header=T,sep="\t")

```


```{r}
sample_Data %>% 
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%y %H:%M", tz="UTC"),
         Date_UTC = if_else(is.na(Date_UTC), as.POSIXct(Collection_Date_UTC, format="%m/%d/%y", tz="UTC"), Date_UTC ), 
         Date_local= format(Date_UTC,tz="US/Alaska")) %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "˚","")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "˚","")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  mutate(., cast= str_c("ctd0",Cast_No.),
         nb=Rosette_position) %>% 
  left_join(ctd_Data)  %>% 
  mutate(., Date_btl_comb = str_c(date, " ",time),
         Date_UTC_btl = as.POSIXct(Date_btl_comb, format="%d-%b-%y %H:%M:%S", tz="UTC") ) -> DY2012_sample_data

colnames(ctd_Data)[5:19] -> cols_2_keep
library(rlang)

DY2012_sample_data %>% 
  select(Sample_Name, 
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Area.within.region,
         Station,
         Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         Date_UTC_btl, 
         !!!syms(cols_2_keep)) -> DY2012_sample_data


readr::write_excel_csv(DY2012_sample_data, file="FinalOME_Merge_DY20-12.csv")
```

