---
title: "Sikuliaq Cruise Metadata Fix"
author: "Zack Gold"
date: "2024-06-21"
output: html_document
---

```{r}
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(readxl)

```

```{r}
ctd_Data <- read.csv(file =here("CTD_raw_BottleFile_SKQ21-12S.csv"), header=T)

ctd_Data %>% 
  slice(1) -> ctd_labels_units

ctd_Data %>% 
  slice(-1) -> ctd_Data

sample_Data <- read.csv(file = here("MachineReadable_CruiseSampleMetadata_SKQ21-12S.csv"), header=T,fileEncoding="UTF-8")

```

```{r}
ctd_Data %>% 
  mutate(., holder1 = str_remove(profile_id,"SKQ202115Sc"),
         Cast = str_remove(holder1,"_btl")) %>% 
           mutate(., Cast = as.numeric(Cast)) -> ctd_Data

ctd_Data$Cast <- as.character(ctd_Data$Cast)
ctd_Data$bottle <- as.character(ctd_Data$bottle)
```


```{r}


sample_Data %>% 
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC),
         Combined_date_local = str_c(Collection_Date_local, " ",Collection_Time_local)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%y %H:%M", tz="UTC"),
                  Date_UTC = if_else(is.na(Date_UTC), as.POSIXct(Collection_Date_UTC, format="%m/%d/%y", tz="UTC"), Date_UTC ), 
         Date_local_check = as.POSIXct(Combined_date_local, format="%m/%d/%y %H:%M", tz="US/Alaska"),
         Date_local_check = if_else(is.na(Date_local_check), as.POSIXct(Combined_date_local, format="%m/%d/%y", tz="UTC"), Date_local_check )) %>%
  mutate(., Date_local= format(Date_UTC,tz="US/Alaska")) %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "˚","")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "˚","")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  mutate(., Cast= as.character(Cast_No.),
         Bottle=as.character(Rosette_position)) %>% 
  left_join(ctd_Data, by = c("Cast" = "Cast", "Bottle" = "bottle")) %>% 
  mutate(., Date_UTC_btl = as.POSIXct(time, format="%Y-%m-%dT%H:%M:%SZ", tz="UTC") )-> SKQ21_sample_data

colnames(ctd_Data)[2:13] -> cols_2_keep
library(rlang)

SKQ21_sample_data %>% 
  select(Sample_Name, 
         Biological_Replicate,
         Technical_Replicate,
         Negative_control, 
         Cruise_ID_short, 
         Cruise_ID_long,
         Cast_No.,
         Rosette_position,
         Field_collection_method,
         Preservation,
         Area.within.region,
         Station,
         Depth_m,
         Sample_volume_ml,
         Personnel_responsible_for_Collecting_Sample,
         Field_Notes,
         Date_UTC_notes=Date_UTC,
         Lat_notes = Lat_dec,
         Lon_notes=Lon_dec,
         Latitude=latitude, 
         Longitude=longitude,
          Date_UTC_btl,
         !!!syms(cols_2_keep)) -> SKQ21_sample_data


readr::write_excel_csv(SKQ21_sample_data, file="FinalOME_Merge_SKQ21-12S.csv")



```

