---
title: "Sikuliaq Cruise Metadata Fix"
author: "Zack Gold"
date: "2024-06-21"
output: html_document
---

# Libraries
```{r}
library(cmocean)
library(ggpubr)
library(patchwork)
library(tidyverse)
library(here)
library(lubridate)
library(measurements)
library(sp)
library(readr)
library(readxl)
library(sf)
library(devtools)
#devtools::install_github("katiejolly/nationalparkcolors")
library(nationalparkcolors)
library(knitr)
library("rnaturalearth")
library("rnaturalearthdata")
library("readxl")
library(parzer)
world <- ne_countries(scale = "medium", returnclass = "sf")
```
# Load CTD Data
```{r}
ctd_Data <- read.csv(file =here("CTD_skq202115s_final_btl_8d75_b94b_6d56.csv"), header=T) #This CTD data comes from Shaun Bell and Phyllis Stabeno in EcoFOCI. Confirm these are QA/QC'd fully before publication.

ctd_Data %>% 
  slice(1) -> ctd_labels_units #save units from data file

ctd_Data %>% 
  slice(-1) -> ctd_Data #remove units from data file for analyses/merging
```

## Format CTD Data for merging
```{r}
ctd_Data %>% 
  mutate(., holder1 = str_remove(profile_id,"SKQ202115Sc"),
         Cast = str_remove(holder1,"_btl")) %>% 
           mutate(., Cast = as.numeric(Cast)) -> ctd_Data

ctd_Data$Cast <- as.character(ctd_Data$Cast)
ctd_Data$bottle <- as.character(ctd_Data$bottle)

ctd_Data %>% 
  mutate(., pressure=as.numeric(pressure),
         Depth_round = round(pressure)) %>% 
  group_by(Cast, Depth_round) %>% 
  count()
```


# Load PMEL Ocean Molecular Ecology Sample Data

```{r}
ome_sample_data <- read.csv(file = here("SKQ202115S_ome_sample_spreadsheet.csv"), header=T,fileEncoding="UTF-8") # These are the transcribed hand written notes from PMEL Ocean Molecular Ecology taken on the cruise

```

## Format & Merge


```{r}

ome_sample_data %>% 
  mutate(., Combined_date = str_c(Collection_Date_UTC, " ",Collection_Time_UTC),
         Combined_date_local = str_c(Collection_Date_local, " ",Collection_Time_local)) %>% 
  mutate(.,  Date_UTC = as.POSIXct(Combined_date, format="%m/%d/%y %H:%M", tz="UTC"),
         Date_local_check = as.POSIXct(Combined_date_local, format="%m/%d/%y %H:%M", tz="US/Alaska")) %>%
  mutate(., Date_local= format(Date_UTC,tz="US/Alaska")) %>% 
  mutate(., Lat_fix =str_remove(Lat, "' N")) %>% 
    mutate(., Lat_fix =str_replace(Lat_fix, "˚","")) %>% 
  mutate(., Lat_dec = measurements::conv_unit(Lat_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_fix =str_remove(Lon, "' W")) %>% 
    mutate(., Lon_fix =str_replace(Lon_fix, "˚","")) %>%
    mutate(., Lon_dec = measurements::conv_unit(Lon_fix,'deg_dec_min','dec_deg')) %>% 
  mutate(., Lon_dec=as.numeric(Lon_dec)) %>% 
  mutate(., , Lon_dec = Lon_dec*-1) %>% 
  mutate(., Cast= as.character(Cast_No.),
         Bottle=as.character(Rosette_position)) %>% 
  dplyr::select(Sample_Name, Biological_Replicate, Technical_Replicate, Negative_control, Cruise_ID_short, Cast, Bottle, Field_collection_method, Preservation, Area.within.region, Station, Sample_volume_ml, Personnel_responsible_for_Collecting_Sample, Field_Notes, Date_UTC, Date_local) %>% 
  left_join(ctd_Data, by = c("Cast" = "Cast", "Bottle" = "bottle")) -> SKQ21_sample_data

write.csv(SKQ21_sample_data, file="SKQ21_sample_data_20240627.csv", row.names = FALSE)
	


```


# Load in Jonah Venture Data
```{r}
SKQ21_MiFish_data <- read.csv(here("MiFishU_F2","MiFishU_F2_tab+taxa.csv"))

SKQ21_16SKelly_data <- read.csv(here("JVB3041_export","16SKelly","16SKelly_tab+taxa.csv"))

SKQ21_18Sv4_data <- read.csv(here("JVB3041_export","18Sv4","18Sv4_tab+taxa.csv"))

SKQ21_18Sv9_89_data <- 
  read.csv(here("JVB3041_export","18Sv9_89","18Sv9_89_tab+taxa.csv"))

SKQ21_18SMachida_data <- read.csv(here("JVB3041_export","18SMachida","18SMachida_tab+taxa.csv"))

SKQ21_ITS1_diatom_data <- read.csv(here("JVB3041_export","ITS1_diatom","ITS1_diatom_tab+taxa.csv"))

SKQ21_UniCOI_data <- read.csv(here("JVB3041_export","UniCOI","UniCOI_tab+taxa.csv"))



JV_sample_data <- read.csv(here("JV243.2_sampleData.csv"))



```
# Phytoplankton

## 18S v4


```{r}
colnames(SKQ21_18Sv4_data)

SKQ21_18Sv4_data  %>% 
  pivot_longer(cols=`JV243.2_18Sv4_GoldZachary_S074784.1`:`JV243.2_18Sv4_GoldZachary_S075167.1`, names_to = "Sample", values_to = "nReads") %>% 
  separate(Sample, into=c("Batch","Run","Marker","PI","SampleId", sep="_")) %>% 
  dplyr::select(-Run, -`_`) %>% 
  left_join(JV_sample_data, by="SampleId") %>% 
  left_join(SKQ21_sample_data, by=c("OwnerSampleId"="Sample_Name")) %>% 
  filter(., str_detect(OwnerSampleId,"SKQ2021")) %>% 
  mutate(., latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))-> full_long_SKQ21_data_set_18Sv4


```


```{r}
full_long_SKQ21_data_set_18Sv4 %>% 
    filter(., nReads >0) %>% 
  group_by(Species) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))


full_long_SKQ21_data_set_18Sv4 %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Genus == "Alexandrium") %>%
  dplyr::select(ESV,Species, Genus, Family) %>%  distinct()


 full_long_SKQ21_data_set_18Sv4 %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Genus == "Alexandrium") %>% 
     group_by(ESV) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))

full_long_SKQ21_data_set_18Sv4 %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Species == "Limacina_retroversa") %>% 
  ggplot(., aes(y=nReads, x=temperature_ch1)) +geom_point()

```


## 18S v9


```{r}
colnames(SKQ21_18Sv9_89_data)

SKQ21_18Sv9_89_data  %>% 
  pivot_longer(cols=`JV243.2_18Sv9_89_GoldZachary_S075168.1`:`JV243.2_18Sv9_89_GoldZachary_S075551.1`, names_to = "Sample", values_to = "nReads") %>% 
  separate(Sample, into=c("Batch","Run","Marker","Mod","PI","SampleId", sep="_")) %>% 
  dplyr::select(-Run, -`_`) %>% 
  left_join(JV_sample_data, by="SampleId") %>% 
  left_join(SKQ21_sample_data, by=c("OwnerSampleId"="Sample_Name")) %>% 
  filter(., str_detect(OwnerSampleId,"SKQ2021")) %>% 
  mutate(., latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))-> full_long_SKQ21_data_set_18Sv9


```


```{r}
full_long_SKQ21_data_set_18Sv9 %>% 
    filter(., nReads >0) %>% 
  group_by(Species) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))


full_long_SKQ21_data_set_18Sv9 %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Genus == "Alexandrium") %>%
  dplyr::select(ESV,Species, Genus, Family) %>%  distinct()


 full_long_SKQ21_data_set_18Sv9 %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Genus == "Alexandrium") %>% 
     group_by(ESV) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))

full_long_SKQ21_data_set_18Sv9 %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Species == "Limacina_retroversa") %>% 
  ggplot(., aes(y=nReads, x=temperature_ch1)) +geom_point()

```


# Invert - Snow Crab

## CO1

```{r}
colnames(SKQ21_UniCOI_data)

SKQ21_UniCOI_data  %>% 
  pivot_longer(cols=`JV243.2_UniCOI_GoldZachary_S074016.1`:`JV243.2_UniCOI_GoldZachary_S074399.1`, names_to = "Sample", values_to = "nReads") %>% 
  separate(Sample, into=c("Batch","Run","Marker","PI","SampleId", sep="_")) %>% 
  dplyr::select(-Run, -`_`) %>% 
  left_join(JV_sample_data, by="SampleId") %>% 
  left_join(SKQ21_sample_data, by=c("OwnerSampleId"="Sample_Name")) %>% 
  filter(., str_detect(OwnerSampleId,"SKQ2021")) %>% 
  mutate(., latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))-> full_long_SKQ21_data_set_CO1


```


```{r}
full_long_SKQ21_data_set_CO1 %>% 
    filter(., nReads >0) %>% 
  group_by(Species) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))


full_long_SKQ21_data_set_CO1 %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Genus == "Calanus") %>%
  dplyr::select(ESV,Species, Genus, Family) %>%  distinct()


 full_long_SKQ21_data_set_CO1 %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Genus == "Calanus") %>% 
     group_by(ESV) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))

full_long_SKQ21_data_set_CO1 %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Species == "Pseudocalanus minutus") %>% 
  ggplot(., aes(y=nReads, x=temperature_ch1)) +geom_point()

```

## 18S Machida

```{r}
colnames(SKQ21_18SMachida_data)

SKQ21_18SMachida_data  %>% 
  pivot_longer(cols=`JV243.2_18SMachida_GoldZachary_S075936.1`:`JV243.2_18SMachida_GoldZachary_S076031.1`, names_to = "Sample", values_to = "nReads") %>% 
  separate(Sample, into=c("Batch","Run","Marker","PI","SampleId", sep="_")) %>% 
  dplyr::select(-Run, -`_`) %>% 
  left_join(JV_sample_data, by="SampleId") %>% 
  left_join(SKQ21_sample_data, by=c("OwnerSampleId"="Sample_Name")) %>% 
  filter(., str_detect(OwnerSampleId,"SKQ2021")) %>% 
  mutate(., latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))-> full_long_SKQ21_data_set_machida


```

```{r}
full_long_SKQ21_data_set_machida %>% 
    filter(., nReads >0) %>% 
  group_by(Species) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))


full_long_SKQ21_data_set_machida %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Order == "Decapoda") %>%
  dplyr::select(ESV,Species, Genus, Family) %>%  distinct()


 full_long_SKQ21_data_set_CO1 %>% 
      filter(., nReads >0) %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Genus == "Calanus") %>% 
     group_by(ESV) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads), Count=length(nReads)) %>% 
  arrange(desc(`sum(nReads)`))

full_long_SKQ21_data_set_CO1 %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Species == "Calanus pacificus") %>% 
  ggplot(., aes(y=nReads, x=temperature_ch1)) +geom_point()

```


```{r}

min_lat <- min(full_long_SKQ21_data_set_mifsh$latitude)
max_lat <- max(full_long_SKQ21_data_set_mifsh$latitude)

min_lon <- min(full_long_SKQ21_data_set_mifsh$longitude)
max_lon <- max(full_long_SKQ21_data_set_mifsh$longitude)

full_long_SKQ21_data_set_mifsh %>% 
    filter(., Species == "Gadus chalcogrammus") -> alaska_pollock

alaska_pollock %>% 
  group_by(Station, longitude,latitude) %>% 
  mutate(., oxy_percentsat_ch1=as.numeric(oxy_percentsat_ch1),
         temperature_ch1=as.numeric(temperature_ch1),
         chlor_fluorescence=as.numeric(chlor_fluorescence),
         salinity_ch1=as.numeric(salinity_ch1)) %>% 
  dplyr::summarise(tot_reads=sum(nReads), oxy_percentsat_ch1=mean(oxy_percentsat_ch1), temperature_ch1=mean(temperature_ch1),chlor_fluorescence=mean(chlor_fluorescence),salinity_ch1=mean(salinity_ch1)) %>% 
    mutate(., PA=if_else(tot_reads >0, "Present", "Absent")) -> alaska_pollock_summed

full_long_SKQ21_data_set %>% 
    filter(., Species == "Boreogadus saida") -> arctic_cod

arctic_cod %>% 
  group_by(Station, longitude,latitude) %>% 
  dplyr::summarise(tot_reads=sum(nReads)) %>% 
    mutate(., PA=if_else(tot_reads >0, "Present", "Absent")) -> arctic_cod_summed



ggplot(data = world) +
    geom_sf() +
    geom_point(data = arctic_cod_summed, aes(x = longitude, y = latitude, colour=PA)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_discrete(name="Arctic Cod Detection") -> SKQ21_arctic_cod_plot

ggplot(data = world) +
    geom_sf() +
    geom_point(data = alaska_pollock_summed, aes(x = longitude, y = latitude, colour=PA)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_discrete(name="Alaska Pollock Detection") -> SKQ21_alaska_pollock_plot_pa


ggplot(data = world) +
    geom_sf() +
    geom_point(data = alaska_pollock_summed, aes(x = longitude, y = latitude, colour=temperature_ch1)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_cmocean("Mean Water Column Temp. ˚C")-> SKQ21_plot_temp
```



# Fish - Gadid
```{r}
SKQ21_MiFish_data %>% 
  pivot_longer(cols=`JV243.2_MiFishU_F2_GoldZachary_S074400.1`:`JV243.2_MiFishU_F2_GoldZachary_S074783.1`, names_to = "Sample", values_to = "nReads") %>% 
  separate(Sample, into=c("Batch","Run","Marker","Mod","PI","SampleId", sep="_")) %>% 
  dplyr::select(-Run, -`_`) %>% 
  left_join(JV_sample_data, by="SampleId") %>% 
  left_join(SKQ21_sample_data, by=c("OwnerSampleId"="Sample_Name")) %>% 
  filter(., str_detect(OwnerSampleId,"SKQ2021")) %>% 
  mutate(., latitude=as.numeric(latitude),
         longitude=as.numeric(longitude))-> full_long_SKQ21_data_set_mifsh


```




```{r}
full_long_SKQ21_data_set_mifsh %>% 
    filter(., nReads >0) %>% 
  group_by(Species) %>% 
  dplyr::summarise(max(nReads), mean(nReads), sum(nReads)) %>% 
  arrange(desc(`sum(nReads)`))


full_long_SKQ21_data_set_mifsh %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Family == "Gadidae") %>%
  dplyr::select(ESV,Species) %>%  distinct()


full_long_SKQ21_data_set_mifsh %>% 
  mutate(., temperature_ch1=as.numeric(temperature_ch1)) %>% 
  filter(., Species == "Gadus chalcogrammus") %>% 
  ggplot(., aes(y=nReads, x=temperature_ch1)) +geom_point()

```

```{r}

min_lat <- min(full_long_SKQ21_data_set_mifsh$latitude)
max_lat <- max(full_long_SKQ21_data_set_mifsh$latitude)

min_lon <- min(full_long_SKQ21_data_set_mifsh$longitude)
max_lon <- max(full_long_SKQ21_data_set_mifsh$longitude)

full_long_SKQ21_data_set_mifsh %>% 
    filter(., Species == "Gadus chalcogrammus") -> alaska_pollock

alaska_pollock %>% 
  group_by(Station, longitude,latitude) %>% 
  mutate(., oxy_percentsat_ch1=as.numeric(oxy_percentsat_ch1),
         temperature_ch1=as.numeric(temperature_ch1),
         chlor_fluorescence=as.numeric(chlor_fluorescence),
         salinity_ch1=as.numeric(salinity_ch1)) %>% 
  dplyr::summarise(tot_reads=sum(nReads), oxy_percentsat_ch1=mean(oxy_percentsat_ch1), temperature_ch1=mean(temperature_ch1),chlor_fluorescence=mean(chlor_fluorescence),salinity_ch1=mean(salinity_ch1)) %>% 
    mutate(., PA=if_else(tot_reads >0, "Present", "Absent")) -> alaska_pollock_summed

full_long_SKQ21_data_set %>% 
    filter(., Species == "Boreogadus saida") -> arctic_cod

arctic_cod %>% 
  group_by(Station, longitude,latitude) %>% 
  dplyr::summarise(tot_reads=sum(nReads)) %>% 
    mutate(., PA=if_else(tot_reads >0, "Present", "Absent")) -> arctic_cod_summed



ggplot(data = world) +
    geom_sf() +
    geom_point(data = arctic_cod_summed, aes(x = longitude, y = latitude, colour=PA)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_discrete(name="Arctic Cod Detection") -> SKQ21_arctic_cod_plot

ggplot(data = world) +
    geom_sf() +
    geom_point(data = alaska_pollock_summed, aes(x = longitude, y = latitude, colour=PA)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_discrete(name="Alaska Pollock Detection") -> SKQ21_alaska_pollock_plot_pa


ggplot(data = world) +
    geom_sf() +
    geom_point(data = alaska_pollock_summed, aes(x = longitude, y = latitude, colour=temperature_ch1)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_cmocean("Mean Water Column Temp. ˚C")-> SKQ21_plot_temp

ggplot(data = world) +
    geom_sf() +
    geom_point(data = alaska_pollock_summed, aes(x = longitude, y = latitude, colour=chlor_fluorescence)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_cmocean("Mean Water Column Chl. Flor.", name="algae")-> SKQ21_plot_chla

ggplot(data = world) +
    geom_sf() +
    geom_point(data = alaska_pollock_summed, aes(x = longitude, y = latitude, colour=oxy_percentsat_ch1)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_cmocean("Mean Water Column Oxygen Saturation", name="ice")-> SKQ21_plot_O2sat

ggplot(data = world) +
    geom_sf() +
    geom_point(data = alaska_pollock_summed, aes(x = longitude, y = latitude, colour=salinity_ch1)) +
    coord_sf(xlim = c(min_lon-2, max_lon+2), ylim = c(min_lat-2, max_lat+2), expand = FALSE) +theme_bw() +xlab("Longitude") +ylab("Latitude") +scale_color_cmocean("Mean Water Column Salinity", name="haline")-> SKQ21_plot_sal



SKQ21_arctic_cod_plot + SKQ21_alaska_pollock_plot_pa+SKQ21_plot_temp +SKQ21_plot_O2sat +SKQ21_plot_chla +SKQ21_plot_sal


```





